import Foundation
import ProjectDescription
import struct ProjectDescription.AbsolutePath
import GekoCore
import GekoGraph
import GekoSupport
import XCTest

@testable import GekoLoader
@testable import GekoSupportTesting

final class CodeCoverageManifestMapperTests: GekoUnitTestCase {
    private typealias Manifest = ProjectDescription.Workspace.GenerationOptions.AutogeneratedWorkspaceSchemes.CodeCoverageMode

    func test_from_returnsTheCorrectValue_whenManifestIsAll() throws {
        // Given
        let temporaryPath = try temporaryPath()
        let generatorPaths = GeneratorPaths(manifestDirectory: temporaryPath)
        var got = Manifest.all

        // When
        try got.resolvePaths(generatorPaths: generatorPaths)

        // Then
        XCTAssertEqual(.all, got)
    }

    func test_from_returnsTheCorrectValue_whenManifestIsRelevant() throws {
        // Given
        let temporaryPath = try temporaryPath()
        let generatorPaths = GeneratorPaths(manifestDirectory: temporaryPath)
        var got = Manifest.relevant

        // When
        try got.resolvePaths(generatorPaths: generatorPaths)

        // Then
        XCTAssertEqual(.relevant, got)
    }

    func test_from_returnsTheCorrectValue_whenManifestIsTargets() throws {
        // Given
        let temporaryPath = try temporaryPath()
        let generatorPaths = GeneratorPaths(manifestDirectory: temporaryPath)
        let targetRef = ProjectDescription.TargetReference(projectPath: nil, target: "Target")
        var got = Manifest.targets([targetRef])
        let nilPath: FilePath? = nil

        // When
        try got.resolvePaths(generatorPaths: generatorPaths)

        // Then
        XCTAssertEqual(
            got,
            .targets([
                TargetReference(
                    projectPath: try generatorPaths.resolveSchemeActionProjectPath(nilPath),
                    name: "Target"
                ),
            ])
        )
    }
}
