import ProjectDescription

let workspace = Workspace(
    name: "Workspace",
    projects: ["./", "Framework1", "Framework2"],
    generationOptions: .options(
        autogeneratedSchemes: [
            .workspace(
                platform: .iOS,
            ),
            .allProjects(
                targetSchemesGrouping: .singleScheme
            )
        ],
        autogeneratedTestPlans: [
            .init(
                name: "GeneratedTestPlan.xctestplan",
                scheme: .init(
                    project: "MainApp",
                    scheme: "MainApp"
                ),
                path: "TestPlans/Geko",
                configurationOptions: .init(
                    targetForVariableExpansion: "AppTests"
                ),
                defaultOptions: .init(
                    environmentVariableEntries: [
                        .init(key: "isUnitTesting", value: "YES"), 
                        .init(key: "isEnableAnimations", value: "YES", enabled: false)
                    ],
                    targetForVariableExpansion: "Framework1",
                    addressSanitizer: .onAndDetectStackUseAfterReturn(),
                    mainThreadCheckerDetectionPolicy: .onAsWarning(),
                    threadPerformanceCheckerRuntimeIssueDetection: .onAsFailure(),
                    runtimeIssueDetection: .off(),
                    checkedAllocations: .onWhenSupportedFallBackToGuardMalloc(),
                ),
                testTargets: .all,
            ),
        ]
    )
)
