import ProjectDescription

let workspace = Workspace(
    name: "Workspace",
    projects: ["./", "Framework1", "Framework2"],
    schemes: [
        Scheme(
            name: "MyWorkspaceScheme",
            buildAction: .buildAction(targets: [], targetSelection: [.scope(platform: .iOS)]),
            testAction: .targets([], targetSelection: [.scope(platform: .iOS)]),
        )
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
