import ProjectDescription

extension Workspace.GenerationOptions.AutogeneratedWorkspaceSchemes {
    public var codeCoverageMode: CodeCoverageMode {
        switch self {
        case let .enabled(codeCoverageMode, _, _, _, _):
            return codeCoverageMode
        case .disabled:
            return .disabled
        }
    }

    public var testingOptions: TestingOptions {
        switch self {
        case let .enabled(_, testingOptions, _, _, _):
            return testingOptions
        case .disabled:
            return []
        }
    }

    public var testLanguage: String? {
        switch self {
        case let .enabled(_, _, language, _, _):
            return language?.identifier
        case .disabled:
            return nil
        }
    }

    public var testRegion: String? {
        switch self {
        case let .enabled(_, _, _, region, _):
            return region
        case .disabled:
            return nil
        }
    }

    public var testScreenCaptureFormat: ScreenCaptureFormat? {
        switch self {
        case let .enabled(_, _, _, _, testScreenCaptureFormat):
            return testScreenCaptureFormat
        case .disabled:
            return nil
        }
    }
}

extension Workspace.GenerationOptions.AutogenerateLocalPodsSchemes {
    /// TestPlans direct property
    public var testPlans: [AbsolutePath] {
        switch self {
        case let .enabled(testPlans):
            return testPlans
        case .disabled:
            return []
        }
    }
}
