import Foundation

public enum Constants {
    public static let versionFileName = ".geko-version"
    public static let binName = "geko"
    public static let gitRepositoryURL = "https://github.com/geko-tech/geko.git"
    public static let githubAPIURL = "https://api.github.com"
    public static let version = "1.0.4"
    public static let projectDescriptionVersion = "release/1.0.0"
    public static let isStage = true
    public static let execSupportMinVersion = "0.6.0"
    public static let bundleName: String = "geko.zip"
    public static let trueValues: [String] = ["1", "true", "TRUE", "yes", "YES"]
    public static let gekoDirectoryName: String = "Geko"

    public static let helpersDirectoryName: String = "ProjectDescriptionHelpers"
    public static let signingDirectoryName: String = "Signing"

    public static let masterKey = "master.key"
    public static let encryptedExtension = "encrypted"
    public static let templatesDirectoryName: String = "Templates"
    public static let stencilsDirectoryName: String = "Stencils"
    public static let vendorDirectoryName: String = "vendor"
    public static let gekoGeneratedFileName = ".geko-generated"
    public static let projectProfilesFileName = "project_profiles.yml"

    /// The cache version.
    /// This should change only when it changes the logic to map a `GekoGraph.Target` to a cached build artifact.
    /// Changing this results in changing the target hash and hence forcing a rebuild of its artifact.
    public static let cacheVersion = "1.3.0"
    public static let cacheLatesBuildFileName = "latest_build"

    public enum GekoUserCacheDirectory {
        public static let name = ".geko"
        public static let versionsDir = "Versions"
    }

    public enum DependenciesDirectory {
        public static let dependenciesFileName = "Dependencies.swift"
        public static let name = "Dependencies"
        public static let graphName = "graph.json"
        public static let lockfilesDirectoryName = "Lockfiles"
        public static let packageSwiftName = "Package.swift"
        public static let cocoapodsLockfileName = "Cocoapods.lock"
        public static let cocoapodsSandboxName = "CocoapodsSandbox.lock"
        public static let packageSandboxName = "PackageSandbox.lock"
        public static let packageResolvedName = "Package.resolved"
        public static let packageBuildDirectoryName = ".build"
        public static let workspaceStateName = "workspace-state.json"
        public static let swiftPackageManagerDirectoryName = "SwiftPackageManager"
        public static let swiftinterfacesDirectoryName = "SwiftInterfaces"
        public static let spmCheckouts = "checkouts"
    }

    public enum DerivedDirectory {
        public static let name = "Derived"
        public static let infoPlists = "InfoPlists"
        public static let entitlements = "Entitlements"
        public static let moduleMaps = "ModuleMaps"
        public static let sources = "Sources"
        public static let resources = "Resources"
        public static let signingKeychain = "signing.keychain"
        public static let dependenciesDerivedDirectory = "geko-derived"
    }

    public enum AsyncQueue {
        public static let directoryName: String = "Queue"
    }

    /// Pass these variables to make custom configuration of geko
    /// These variables are not supposed to be used by end users
    /// But only eg. for acceptance tests and other cases needed internally
    public enum EnvironmentVariables: String, CaseIterable {
        case verbose = "GEKO_CONFIG_VERBOSE"
        case colouredOutput = "GEKO_CONFIG_COLOURED_OUTPUT"
        case versionsDirectory = "GEKO_CONFIG_VERSIONS_DIRECTORY"
        case forceConfigCacheDirectory = "GEKO_CONFIG_FORCE_CONFIG_CACHE_DIRECTORY"
        case detailedLog = "GEKO_CONFIG_DETAILED_LOG"
        case osLog = "GEKO_CONFIG_OS_LOG"

        case inspectSourceRef = "GEKO_INSPECT_SOURCE_REF"
        case inspectTargetRef = "GEKO_INSPECT_TARGET_REF"
        case cloudAccessKey = "GEKO_CLOUD_ACCESS_KEY"
        case cloudSecretKey = "GEKO_CLOUD_SECRET_KEY"
        case statsOutput = "GEKO_CONFIG_STATS_OUTPUT"
        case cacheTargetHashesSave = "GEKO_CONFIG_CACHE_TARGET_HASHES_SAVE"
        case forceConfigLogDirectory = "GEKO_CONFIG_LOG_STORAGE_DIR"
        case cocoapodsCacheDirectory = "GEKO_CONFIG_COCOAPODS_CACHE_DIR"
        case cocoapodsRepoCacheDirectory = "GEKO_CONFIG_COCOAPODS_REPO_CACHE_DIR"
        case requestTimeout = "GEKO_REQUEST_TIMEOUT"
        case swiftModuleCache = "GEKO_SWIFTMODULE_CACHE_ENABLED"
        case forceBuildCacheDirectory = "GEKO_CONFIG_BUILD_CACHE_DIR"

        // Hidden variables meant for testing

        /// `gekoBinaryPath` is used for specifying the exact geko binary in geko tasks.
        public static let gekoBinaryPath = "GEKO_CONFIG_BINARY_PATH"
    }

    public enum AutogeneratedScheme {
        public static let binariesSchemeNamePrefix: String = "ProjectCache-Binaries"
        public static let bundlesSchemeNamePrefix: String = "ProjectCache-Bundles"
    }

    public enum Plugins {
        public static let executables = "Executables"
        public static let plugisSandbox = "PluginsSandbox.lock"
        public static let mappers = "Mappers"
        public static let infoFileName = "info.json"
    }
}
