import Crypto
import Foundation
import ProjectDescription
import XcodeProj

public extension [AutogeneratedXCTestPlanDescriptor.TestTarget] {

    func mapTestTargets() -> [AutogeneratedXCTestPlan.TestTarget] {
        map { target in
            AutogeneratedXCTestPlan.TestTarget(
                target: AutogeneratedXCTestPlan.TestTargetReference(
                    containerPath: target.containerPath,
                    identifier: target.pbxTarget.uuid,
                    name: target.pbxTarget.name
                ),
                selectedTests: target.selectedTests.isEmpty ? nil : target.selectedTests,
                skippedTests: target.skippedTests.isEmpty ? nil : target.skippedTests,
                enabled: target.isEnabled ? nil : false,
                parallelizable: target.isParallelizable ? true : nil,
            )
        }
    }
}

/// Describes a generated `.xctestplan` file.
public struct AutogeneratedXCTestPlanDescriptor: Equatable {
    /// Absolute path where the generated `.xctestplan` will be written.
    public let path: AbsolutePath

    /// Options applied to the plan's `Default` configuration.
    public let configurationOptions: AutogeneratedTestPlan.Options?

    /// Options applied as the plan's global defaults, used when a configuration doesn't override them.
    public let defaultOptions: AutogeneratedTestPlan.Options?

    /// Test target used to expand variable references in `configurationOptions`.
    public let configurationOptionsTargetForVariableExpansion: TestTarget?

    /// Test target used to expand variable references in `defaultOptions`.
    public let defaultOptionsTargetForVariableExpansion: TestTarget?

    /// Test targets included in the plan.
    public let testTargets: [TestTarget]

    public struct TestTarget: Equatable {
        /// Reference to the PBX target. Its `uuid` becomes the `identifier` in the test plan.
        public let pbxTarget: PBXTarget

        /// `container:` relative path to the `.xcodeproj` that owns the target, as used by Xcode.
        public let containerPath: String

        /// Whether the target runs or is skipped in the plan.
        public let isEnabled: Bool

        /// Whether the target isParallelizable.
        public let isParallelizable: Bool

        /// A list of specific tests to include in the plan.
        public let selectedTests: [String]

        /// A list of specific tests to exclude from the plan.
        public let skippedTests: [String]

        public init(
            pbxTarget: PBXTarget,
            containerPath: String,
            isEnabled: Bool,
            isParallelizable: Bool,
            selectedTests: [String],
            skippedTests: [String]
        ) {
            self.pbxTarget = pbxTarget
            self.containerPath = containerPath
            self.isEnabled = isEnabled
            self.isParallelizable = isParallelizable
            self.selectedTests = selectedTests
            self.skippedTests = skippedTests
        }
    }

    public init(
        path: AbsolutePath,
        configurationOptions: AutogeneratedTestPlan.Options?,
        defaultOptions: AutogeneratedTestPlan.Options?,
        configurationOptionsTargetForVariableExpansion: TestTarget?,
        defaultOptionsTargetForVariableExpansion: TestTarget?,
        testTargets: [TestTarget]
    ) {
        self.path = path
        self.configurationOptions = configurationOptions
        self.defaultOptions = defaultOptions
        self.configurationOptionsTargetForVariableExpansion = configurationOptionsTargetForVariableExpansion
        self.defaultOptionsTargetForVariableExpansion = defaultOptionsTargetForVariableExpansion
        self.testTargets = testTargets
    }

    /// Encodes the descriptor into the Xcode `.xctestplan` JSON format.
    ///
    /// - Note: Must be called after the owning `.xcodeproj` has been written so that
    ///   `pbxTarget.uuid` returns stable blueprint identifiers.
    public func encode() throws -> Data {
        let plan = AutogeneratedXCTestPlan(
            testTargets: testTargets.mapTestTargets(),
            configurations: [
                AutogeneratedXCTestPlan.Configuration(
                    id: configurationID,
                    name: "Default",
                    options: configurationOptions?.map(targetForVariableExpansion: configurationOptionsTargetForVariableExpansion) ?? .empty
                ),
            ],
            defaultOptions: defaultOptions?.map(targetForVariableExpansion: defaultOptionsTargetForVariableExpansion) ?? .empty,
            version: 1
        )

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        return try encoder.encode(plan)
    }

    /// Deterministic UUID derived from the plan's absolute path.
    ///
    /// Keeps the configuration ID stable across regenerations (no git churn when a plan is
    /// pinned to a checked-in location) while being unique per plan.
    private var configurationID: UUID {
        let digest = Array(SHA256.hash(data: Data(path.pathString.utf8)).prefix(16))
        return UUID(uuid: (
            digest[0], digest[1], digest[2], digest[3],
            digest[4], digest[5], digest[6], digest[7],
            digest[8], digest[9], digest[10], digest[11],
            digest[12], digest[13], digest[14], digest[15]
        ))
    }
}
