import Foundation
import ProjectDescription
import GekoSupport
import GekoCore
import GekoGraph
import GekoLoader

enum AutogeneratedXCTestPlanDescriptorGeneratorError: FatalError {
    case targetForVariableExpansionNotFound(target: String)
    case specificTestableTargetNotFound(testPlan: String, target: String)
    case generatedProjectNotFound(targetName: String, path: String)

    var type: ErrorType {
        switch self {
        case .targetForVariableExpansionNotFound, .specificTestableTargetNotFound, .generatedProjectNotFound:
            return .abort
        }
    }

    var description: String {
        switch self {
        case let .targetForVariableExpansionNotFound(target):
            return "Target '\(target)' specified for variable expansion not found."
        case let .specificTestableTargetNotFound(testPlan, target):
            return "Test plan '\(testPlan)'. Target '\(target)' specified for testing was not found. Verify that the target exists and is spelled correctly, or change the missing target policy to '.excludeTarget' or '.skipTestPlan'."
        case let .generatedProjectNotFound(targetName, path):
            return "Could not find the generated project for target '\(targetName)' at path '\(path)'. This is likely an internal error. Please report this issue."
        }
    }
}

protocol AutogeneratedXCTestPlanDescriptorGenerating: AnyObject {
    func autogeneratedXCTestPlanDescriptorsAndGenerateMetadata(
        graphTraverser: GraphTraversing,
        generatedProjects: [AbsolutePath: GeneratedProject],
        sideTable: GraphSideTable
    ) throws -> ([AutogeneratedXCTestPlanDescriptor], GenerateMetadata)
}

/// Outcome of resolving a variable-expansion target for a test plan.
private enum VariableExpansionTargetResolution {
    /// No variable-expansion target was configured, or a missing one was excluded.
    case none
    /// The variable-expansion target was resolved.
    case resolved(AutogeneratedXCTestPlanDescriptor.TestTarget)
    /// A requested target is missing and the policy is `.skipTestPlan`.
    case skipTestPlan
}

final class AutogeneratedXCTestPlanDescriptorGenerator: AutogeneratedXCTestPlanDescriptorGenerating {

    // MARK: - AutogeneratedXCTestPlanDescriptorGenerating

    func autogeneratedXCTestPlanDescriptorsAndGenerateMetadata(
        graphTraverser: GraphTraversing,
        generatedProjects: [AbsolutePath: GeneratedProject],
        sideTable: GraphSideTable
    ) throws -> ([AutogeneratedXCTestPlanDescriptor], GenerateMetadata) {

        let allTargets = graphTraverser.allInternalTargets()
        let rootPath = graphTraverser.workspace.xcWorkspacePath.parentDirectory
        let generatorPaths = GeneratorPaths(manifestDirectory: graphTraverser.workspace.path)

        let autogeneratedXCTestPlanDescriptors = try mapAutogeneratedXCTestPlanDescriptors(
            autogeneratedTestPlans: graphTraverser.workspace.generationOptions.autogeneratedTestPlans,
            generatorPaths: generatorPaths,
            generatedProjects: generatedProjects,
            allTargets: allTargets,
            rootPath: rootPath
        )

        let allTestTargets = try mapAllTargetsToTestTargets(
            allTargets: allTargets,
            rootPath: rootPath,
            generatedProjects: generatedProjects
        ).mapTestTargets()

        let generateMetadata = GenerateMetadata(
            workspaceName: graphTraverser.workspace.name,
            cacheEnabled: sideTable.workspace.cacheEnabled,
            focusedTargets: sideTable.workspace.focusedTargets,
            allTestTargets: allTestTargets
        )

        return (autogeneratedXCTestPlanDescriptors, generateMetadata)
    }

    // MARK: - Test plan descriptors

    private func mapAutogeneratedXCTestPlanDescriptors(
        autogeneratedTestPlans: [AutogeneratedTestPlan],
        generatorPaths: GeneratorPaths,
        generatedProjects: [AbsolutePath: GeneratedProject],
        allTargets: Set<GraphTarget>,
        rootPath: AbsolutePath,
    ) throws -> [AutogeneratedXCTestPlanDescriptor] {
        try autogeneratedTestPlans.compactMap { autogeneratedTestPlan in
            try descriptor(
                for: autogeneratedTestPlan,
                generatorPaths: generatorPaths,
                generatedProjects: generatedProjects,
                allTargets: allTargets,
                rootPath: rootPath
            )
        }
    }

    /// Builds the descriptor for a single test plan, or `nil` when the plan should be skipped
    /// (e.g. a requested target is missing and the policy is `.skipTestPlan`).
    private func descriptor(
        for autogeneratedTestPlan: AutogeneratedTestPlan,
        generatorPaths: GeneratorPaths,
        generatedProjects: [AbsolutePath: GeneratedProject],
        allTargets: Set<GraphTarget>,
        rootPath: AbsolutePath,
    ) throws -> AutogeneratedXCTestPlanDescriptor? {
        let path = try autogeneratedTestPlan.resolvePath(generatorPaths: generatorPaths)

        let configurationOptionsTargetForVariableExpansion: AutogeneratedXCTestPlanDescriptor.TestTarget?
        switch try descriptorTestTargetForVariableExpansion(
            target: autogeneratedTestPlan.configurationOptions?.targetForVariableExpansion,
            missingTargetPolicy: autogeneratedTestPlan.missingTargetPolicy,
            testPlan: autogeneratedTestPlan.name,
            allTargets: allTargets,
            rootPath: rootPath,
            generatedProjects: generatedProjects
        ) {
        case .none:
            configurationOptionsTargetForVariableExpansion = nil
        case let .resolved(testTarget):
            configurationOptionsTargetForVariableExpansion = testTarget
        case .skipTestPlan:
            return nil
        }

        let defaultOptionsTargetForVariableExpansion: AutogeneratedXCTestPlanDescriptor.TestTarget?
        switch try descriptorTestTargetForVariableExpansion(
            target: autogeneratedTestPlan.defaultOptions?.targetForVariableExpansion,
            missingTargetPolicy: autogeneratedTestPlan.missingTargetPolicy,
            testPlan: autogeneratedTestPlan.name,
            allTargets: allTargets,
            rootPath: rootPath,
            generatedProjects: generatedProjects
        ) {
        case .none:
            defaultOptionsTargetForVariableExpansion = nil
        case let .resolved(testTarget):
            defaultOptionsTargetForVariableExpansion = testTarget
        case .skipTestPlan:
            return nil
        }

        let testTargets: [AutogeneratedXCTestPlanDescriptor.TestTarget]
        switch autogeneratedTestPlan.testTargetSelection {
        case .all:
            testTargets = try mapAllTargetsToTestTargets(
                allTargets: allTargets,
                rootPath: rootPath,
                generatedProjects: generatedProjects
            )
        case let .specific(specificTargets):
            guard let graphTargets = try resolveSpecificTargets(
                specificTargets,
                missingTargetPolicy: autogeneratedTestPlan.missingTargetPolicy,
                testPlan: autogeneratedTestPlan.name,
                allTargets: allTargets
            ) else {
                return nil
            }
            testTargets = try mapTargetsToTestTargets(
                targets: graphTargets,
                rootPath: rootPath,
                generatedProjects: generatedProjects
            )
        }

        return AutogeneratedXCTestPlanDescriptor(
            path: path,
            configurationOptions: autogeneratedTestPlan.configurationOptions,
            defaultOptions: autogeneratedTestPlan.defaultOptions,
            configurationOptionsTargetForVariableExpansion: configurationOptionsTargetForVariableExpansion,
            defaultOptionsTargetForVariableExpansion: defaultOptionsTargetForVariableExpansion,
            testTargets: testTargets
        )
    }

    /// Resolves the explicitly listed targets, honoring the missing-target policy.
    ///
    /// Returns `nil` when the whole test plan should be skipped (`.skipTestPlan` policy).
    private func resolveSpecificTargets(
        _ specificTargets: [AutogeneratedTestableTarget],
        missingTargetPolicy: AutogeneratedTestPlan.MissingTargetPolicy,
        testPlan: String,
        allTargets: Set<GraphTarget>,
    ) throws -> [(AutogeneratedTestableTarget, GraphTarget)]? {
        var graphTargets: [(AutogeneratedTestableTarget, GraphTarget)] = []

        for specificTarget in specificTargets {
            guard let graphTarget = allTargets.first(where: { $0.target.name == specificTarget.target.target.targetName }) else {
                switch missingTargetPolicy {
                case let .skipTestPlan(notification):
                    warnIfNeeded(
                        notification,
                        testPlan: testPlan,
                        target: specificTarget.target.target.name,
                        action: "The test plan will be skipped."
                    )
                    return nil
                case let .skipTarget(notification):
                    warnIfNeeded(
                        notification,
                        testPlan: testPlan,
                        target: specificTarget.target.target.name,
                        action: "The target will be excluded from the test plan."
                    )
                    continue
                case .fail:
                    throw AutogeneratedXCTestPlanDescriptorGeneratorError.specificTestableTargetNotFound(
                        testPlan: testPlan,
                        target: specificTarget.target.target.name
                    )
                }
            }

            graphTargets.append((specificTarget, graphTarget))
        }

        return graphTargets
    }

    private func warnIfNeeded(
        _ notification: AutogeneratedTestPlan.MissingTargetPolicy.Notification,
        testPlan: String,
        target: String,
        action: String,
    ) {
        guard case .warning = notification else { return }
        logger.warning(
            "Test plan '\(testPlan)'. Target '\(target)' specified for testing was not found. Verify that the target exists and is spelled correctly. \(action)"
        )
    }

    private func descriptorTestTargetForVariableExpansion(
        target: String?,
        missingTargetPolicy: AutogeneratedTestPlan.MissingTargetPolicy,
        testPlan: String,
        allTargets: Set<GraphTarget>,
        rootPath: AbsolutePath,
        generatedProjects: [AbsolutePath: GeneratedProject],
    ) throws -> VariableExpansionTargetResolution {
        guard let target else { return .none }

        guard let graphTarget = allTargets.first(where: { $0.target.name == target }) else {
            switch missingTargetPolicy {
            case let .skipTestPlan(notification):
                warnIfNeeded(
                    notification,
                    testPlan: testPlan,
                    target: target,
                    action: "The test plan will be skipped."
                )
                return .skipTestPlan
            case let .skipTarget(notification):
                warnIfNeeded(
                    notification,
                    testPlan: testPlan,
                    target: target,
                    action: "The variable expansion target will be ignored."
                )
                return .none
            case .fail:
                throw AutogeneratedXCTestPlanDescriptorGeneratorError.targetForVariableExpansionNotFound(target: target)
            }
        }

        let testTarget = try descriptorTestTarget(
            rootPath: rootPath,
            generatedProjects: generatedProjects,
            target: (AutogeneratedTestableTarget(TestableTarget(stringLiteral: target)), graphTarget)
        )
        return .resolved(testTarget)
    }

    // MARK: - Test targets

    private func mapAllTargetsToTestTargets(
        allTargets: Set<GraphTarget>,
        rootPath: AbsolutePath,
        generatedProjects: [AbsolutePath: GeneratedProject],
    ) throws -> [AutogeneratedXCTestPlanDescriptor.TestTarget] {
        let targets = allTargets.filter(\.target.product.testsBundle).map { graphTarget in
            (AutogeneratedTestableTarget(TestableTarget(target: TargetReference(stringLiteral: graphTarget.target.name))), graphTarget)
        }
        return try mapTargetsToTestTargets(targets: targets, rootPath: rootPath, generatedProjects: generatedProjects)
    }

    private func mapTargetsToTestTargets(
        targets: [(testableTarget: AutogeneratedTestableTarget, graphTarget: GraphTarget)],
        rootPath: AbsolutePath,
        generatedProjects: [AbsolutePath: GeneratedProject],
    ) throws -> [AutogeneratedXCTestPlanDescriptor.TestTarget] {
        let descriptoTargets = try targets.map { target in
            try descriptorTestTarget(rootPath: rootPath, generatedProjects: generatedProjects, target: target)
        }
        return descriptoTargets.sorted(by: { $0.pbxTarget.name < $1.pbxTarget.name })
    }

    private func descriptorTestTarget(
        rootPath: AbsolutePath,
        generatedProjects: [AbsolutePath: GeneratedProject],
        target: (testableTarget: AutogeneratedTestableTarget, graphTarget: GraphTarget)
    ) throws -> AutogeneratedXCTestPlanDescriptor.TestTarget {

        let (testableTarget, graphTarget) = target
        let xcodeProjectPath = graphTarget.project.xcodeProjPath

        guard
            let generatedProject = generatedProjects[xcodeProjectPath],
            let pbxTarget = generatedProject.targets[graphTarget.target.name]
        else {
            throw AutogeneratedXCTestPlanDescriptorGeneratorError.generatedProjectNotFound(
                targetName: graphTarget.target.name,
                path: xcodeProjectPath.pathString
            )
        }

        let containerRelativePath = xcodeProjectPath.relative(to: rootPath).pathString

        return AutogeneratedXCTestPlanDescriptor.TestTarget(
            pbxTarget: pbxTarget,
            containerPath: "container:\(containerRelativePath)",
            isEnabled: !testableTarget.target.isSkipped,
            isParallelizable: testableTarget.target.isParallelizable,
            selectedTests: testableTarget.selectedTests,
            skippedTests: testableTarget.skippedTests
        )
    }
}
