@preconcurrency import ProjectDescription
import Foundation

let workspace = Workspace(
    name: "App",
    projects: [],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .enabled()
    )
)
