import Foundation
import GekoGraph
import GekoGraphTesting
import ProjectDescription
import XCTest
import GekoCore

@testable import GekoGenerator
@testable import GekoSupportTesting

final class AutogeneratedSchemesProjectsGraphMapperTests: GekoUnitTestCase {

    func test_map_projectSchemes_allProjects_singleScheme() async throws {
        // Given
        let subject = AutogeneratedSchemesProjectsGraphMapper()
        let (targets, projectPath) = try makeProjectTargets()
        let project = Project.test(
            path: projectPath,
            name: "Project",
            targets: targets
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [
                .allProjects(
                    targetSchemesGrouping: .singleScheme,
                    codeCoverageEnabled: false,
                    testingOptions: []
                ),
            ]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        let sideEffects = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        XCTAssertEmpty(sideEffects)

        let expected = [
            makeScheme(
                name: "Project",
                buildTargetNames: ["A", "ADemo", "B"],
                testTargetNames: ["ATests", "BIntegrationTests", "BSnapshotTests", "BTests", "BUITests"],
                runTargetName: nil,
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false
            ),
        ]

        XCTAssertEqual(try XCTUnwrap(graph.projects[projectPath]).schemes, expected)
    }

    func test_map_projectSchemes_allProjects_byNameSuffix() async throws {
        // Given
        let subject = AutogeneratedSchemesProjectsGraphMapper()
        let (targets, projectPath) = try makeProjectTargets(includeAllIntegrationTests: true)
        let project = Project.test(
            path: projectPath,
            name: "Project",
            targets: targets
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [
                .allProjects(
                    targetSchemesGrouping: .byNameSuffix(
                        build: [],
                        test: ["Tests", "UITests", "IntegrationTests", "SnapshotTests"],
                        run: ["Demo"]
                    ),
                    codeCoverageEnabled: false,
                    testingOptions: []
                ),
            ]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let expected = [
            makeScheme(
                name: "A",
                buildTargetNames: ["A", "ADemo"],
                testTargetNames: ["ATests"],
                runTargetName: "ADemo",
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false
            ),
            makeScheme(
                name: "AllIntegrationTests",
                buildTargetNames: ["AllIntegrationTests"],
                testTargetNames: ["AllIntegrationTests"],
                runTargetName: nil,
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false
            ),
            makeScheme(
                name: "B",
                buildTargetNames: ["B"],
                testTargetNames: ["BIntegrationTests", "BSnapshotTests", "BTests", "BUITests"],
                runTargetName: "B",
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false
            ),
        ]

        XCTAssertEqual(try XCTUnwrap(graph.projects[projectPath]).schemes, expected)
    }

    func test_map_projectSchemes_allProjects_notGrouped() async throws {
        // Given
        let subject = AutogeneratedSchemesProjectsGraphMapper()
        let (targets, projectPath) = try makeProjectTargets()
        let project = Project.test(
            path: projectPath,
            name: "Project",
            targets: targets
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [
                .allProjects(
                    targetSchemesGrouping: .notGrouped,
                    codeCoverageEnabled: false,
                    testingOptions: []
                ),
            ]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let expected = [
            makeScheme(name: "A", buildTargetNames: ["A"], testTargetNames: [], runTargetName: nil, projectPath: projectPath, coverage: false, parallelizable: false, randomExecution: false),
            makeScheme(name: "ADemo", buildTargetNames: ["ADemo"], testTargetNames: [], runTargetName: "ADemo", projectPath: projectPath, coverage: false, parallelizable: false, randomExecution: false),
            makeScheme(name: "ATests", buildTargetNames: ["ATests"], testTargetNames: ["ATests"], runTargetName: nil, projectPath: projectPath, coverage: false, parallelizable: false, randomExecution: false),
            makeScheme(name: "B", buildTargetNames: ["B"], testTargetNames: [], runTargetName: "B", projectPath: projectPath, coverage: false, parallelizable: false, randomExecution: false),
            makeScheme(name: "BIntegrationTests", buildTargetNames: ["BIntegrationTests"], testTargetNames: ["BIntegrationTests"], runTargetName: nil, projectPath: projectPath, coverage: false, parallelizable: false, randomExecution: false),
            makeScheme(name: "BSnapshotTests", buildTargetNames: ["BSnapshotTests"], testTargetNames: ["BSnapshotTests"], runTargetName: nil, projectPath: projectPath, coverage: false, parallelizable: false, randomExecution: false),
            makeScheme(name: "BTests", buildTargetNames: ["BTests"], testTargetNames: ["BTests"], runTargetName: nil, projectPath: projectPath, coverage: false, parallelizable: false, randomExecution: false),
            makeScheme(name: "BUITests", buildTargetNames: ["BUITests"], testTargetNames: ["BUITests"], runTargetName: nil, projectPath: projectPath, coverage: false, parallelizable: false, randomExecution: false),
        ]

        XCTAssertEqual(try XCTUnwrap(graph.projects[projectPath]).schemes, expected)
    }

    func test_map_projectSchemes_allProjects_pods() async throws {
        // Given
        let subject = AutogeneratedSchemesProjectsGraphMapper()
        let targetB = Target.test(name: "B", product: .staticFramework)
        let targetBTests = Target.test(
            name: "BTests",
            product: .unitTests,
            dependencies: [.target(name: "B")]
        )
        let targetBUITests = Target.test(
            name: "BUITests",
            product: .uiTests,
            dependencies: [.target(name: "B")]
        )
        let targetBIntegrationTests = Target.test(
            name: "BIntegrationTests",
            product: .unitTests,
            dependencies: [.target(name: "B")]
        )
        let targetBSnapshotTests = Target.test(
            name: "BSnapshotTests",
            product: .unitTests,
            dependencies: [
                .target(name: "B"),
                .target(name: "A"),
            ]
        )
        let targetBDemo = Target.test(
            name: "BDemo",
            product: .app,
            dependencies: [.target(name: "B")]
        )
        let targetA = Target.test(name: "A", product: .bundle)
        let targetBDemoTwo = Target.test(
            name: "B2Demo",
            product: .app,
            dependencies: [
                .target(name: "B"),
            ]
        )

        let projectPath = try temporaryPath()
        let testPlans = try createFiles(["a.xctestplan", "b.xctestplan", "c.xctestplan"])
        let project = Project.test(
            path: projectPath,
            name: "Project",
            targets: [
                targetA,
                targetB,
                targetBTests,
                targetBUITests,
                targetBIntegrationTests,
                targetBSnapshotTests,
                targetBDemo,
                targetBDemoTwo
            ]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [
                .allProjects(
                    targetSchemesGrouping: .pods,
                    codeCoverageEnabled: false,
                    testingOptions: [],
                    testPlans: testPlans.map { $0.pathString }
                ),
            ]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let expected: [Scheme] = [
            makeScheme(
                name: "B",
                buildTargetNames: ["B"],
                runTargetName: nil,
                projectPath: projectPath,
                coverage: true,
                parallelizable: false,
                randomExecution: false,
                testAction: .init(
                    targets: [],
                    arguments: nil,
                    configurationName: "Debug",
                    attachDebugger: true,
                    coverage: false,
                    codeCoverageTargets: [],
                    expandVariableFromTarget: nil,
                    preActions: [],
                    postActions: [],
                    diagnosticsOptions: .init(mainThreadCheckerEnabled: false, performanceAntipatternCheckerEnabled: false),
                    testPlans: testPlans.map { TestPlan(path: $0, testTargets: [], isDefault: $0 == testPlans.first) }
                )
            ),
            makeScheme(
                name: "B2Demo",
                buildTargetNames: ["B2Demo"],
                runTargetName: nil,
                projectPath: projectPath,
                coverage: true,
                parallelizable: false,
                randomExecution: false
            ),
            makeScheme(
                name: "BDemo",
                buildTargetNames: ["BDemo"],
                runTargetName: nil,
                projectPath: projectPath,
                coverage: true,
                parallelizable: false,
                randomExecution: false
            ),
        ]

        XCTAssertEqual(try XCTUnwrap(graph.projects[projectPath]).schemes, expected)
    }

    func test_map_projectSchemes_userSchemesPreserved() async throws {
        // Given
        let subject = AutogeneratedSchemesProjectsGraphMapper()
        let (targets, projectPath) = try makeProjectTargets()
        let project = Project.test(
            path: projectPath,
            name: "Project",
            targets: targets,
            schemes: [
                makeScheme(
                    name: "A",
                    buildTargetNames: ["A"],
                    testTargetNames: [],
                    runTargetName: nil,
                    projectPath: projectPath,
                    coverage: true,
                    parallelizable: false,
                    randomExecution: false
                ),
            ]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [
                .allProjects(
                    targetSchemesGrouping: .byNameSuffix(
                        build: [],
                        test: ["Tests", "UITests", "IntegrationTests", "SnapshotTests"],
                        run: ["Demo"]
                    ),
                    codeCoverageEnabled: false,
                    testingOptions: []
                ),
            ]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let expected = [
            makeScheme(
                name: "A",
                buildTargetNames: ["A"],
                testTargetNames: [],
                runTargetName: nil,
                projectPath: projectPath,
                coverage: true,
                parallelizable: false,
                randomExecution: false
            ),
            makeScheme(
                name: "B",
                buildTargetNames: ["B"],
                testTargetNames: ["BIntegrationTests", "BSnapshotTests", "BTests", "BUITests"],
                runTargetName: "B",
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false
            ),
        ]

        XCTAssertEqual(try XCTUnwrap(graph.projects[projectPath]).schemes, expected)
    }

    func test_map_projectSchemes_coverageEnabled() async throws {
        // Given
        let subject = AutogeneratedSchemesProjectsGraphMapper()
        let (targets, projectPath) = try makeProjectTargets()
        let project = Project.test(
            path: projectPath,
            name: "Project",
            targets: targets
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [
                .allProjects(
                    targetSchemesGrouping: .byNameSuffix(
                        build: [],
                        test: ["Tests", "UITests", "IntegrationTests", "SnapshotTests"],
                        run: ["Demo"]
                    ),
                    codeCoverageEnabled: true,
                    testingOptions: []
                ),
            ]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let expected = [
            makeScheme(
                name: "A",
                buildTargetNames: ["A", "ADemo"],
                testTargetNames: ["ATests"],
                runTargetName: "ADemo",
                projectPath: projectPath,
                coverage: true,
                parallelizable: false,
                randomExecution: false
            ),
            makeScheme(
                name: "B",
                buildTargetNames: ["B"],
                testTargetNames: ["BIntegrationTests", "BSnapshotTests", "BTests", "BUITests"],
                runTargetName: "B",
                projectPath: projectPath,
                coverage: true,
                parallelizable: false,
                randomExecution: false
            ),
        ]

        XCTAssertEqual(try XCTUnwrap(graph.projects[projectPath]).schemes, expected)
    }

    func test_map_projectSchemes_testingOptions() async throws {
        // Given
        let subject = AutogeneratedSchemesProjectsGraphMapper()
        let (targets, projectPath) = try makeProjectTargets()
        let project = Project.test(
            path: projectPath,
            name: "Project",
            targets: targets
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [
                .allProjects(
                    targetSchemesGrouping: .byNameSuffix(
                        build: [],
                        test: ["Tests", "UITests", "IntegrationTests", "SnapshotTests"],
                        run: ["Demo"]
                    ),
                    codeCoverageEnabled: false,
                    testingOptions: [.parallelizable, .randomExecutionOrdering]
                ),
            ]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let expected = [
            makeScheme(
                name: "A",
                buildTargetNames: ["A", "ADemo"],
                testTargetNames: ["ATests"],
                runTargetName: "ADemo",
                projectPath: projectPath,
                coverage: false,
                parallelizable: true,
                randomExecution: true
            ),
            makeScheme(
                name: "B",
                buildTargetNames: ["B"],
                testTargetNames: ["BIntegrationTests", "BSnapshotTests", "BTests", "BUITests"],
                runTargetName: "B",
                projectPath: projectPath,
                coverage: false,
                parallelizable: true,
                randomExecution: true
            ),
        ]

        XCTAssertEqual(try XCTUnwrap(graph.projects[projectPath]).schemes, expected)
    }

    func test_map_projectSchemes_runArguments() async throws {
        // Given
        let subject = AutogeneratedSchemesProjectsGraphMapper()
        let (targets, projectPath) = try makeProjectTargets(
            runEnvironmentVariables: ["A": EnvironmentVariable(value: "B", isEnabled: true)],
            runLaunchArguments: [.init(name: "--run-argument", isEnabled: true)]
        )
        let project = Project.test(
            path: projectPath,
            name: "Project",
            targets: targets
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [
                .allProjects(
                    targetSchemesGrouping: .byNameSuffix(
                        build: [],
                        test: ["Tests", "UITests", "IntegrationTests", "SnapshotTests"],
                        run: ["Demo"]
                    ),
                    codeCoverageEnabled: false,
                    testingOptions: []
                ),
            ]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let expected = [
            makeScheme(
                name: "A",
                buildTargetNames: ["A", "ADemo"],
                testTargetNames: ["ATests"],
                runTargetName: "ADemo",
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false,
                runActionArguments: .init(
                    environmentVariables: ["A": EnvironmentVariable(value: "B", isEnabled: true)],
                    launchArguments: []
                )
            ),
            makeScheme(
                name: "B",
                buildTargetNames: ["B"],
                testTargetNames: ["BIntegrationTests", "BSnapshotTests", "BTests", "BUITests"],
                runTargetName: "B",
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false,
                runActionArguments: .init(
                    environmentVariables: [:],
                    launchArguments: [.init(name: "--run-argument", isEnabled: true)]
                )
            ),
        ]

        XCTAssertEqual(try XCTUnwrap(graph.projects[projectPath]).schemes, expected)
    }

    func test_map_projectSchemes_test_arguments() async throws {
        // Given
        let subject = AutogeneratedSchemesProjectsGraphMapper()
        let targetB = Target.test(name: "B", product: .app)
        let targetBTests = Target.test(
            name: "BTests",
            product: .unitTests,
            environmentVariables: [
                "a": EnvironmentVariable(value: "1", isEnabled: true),
                "b": EnvironmentVariable(value: "2", isEnabled: false),
                "c": EnvironmentVariable(value: "3", isEnabled: true),
            ],
            dependencies: [
                .target(name: "B"),
                .target(name: "A"),
            ],
            launchArguments: [
                .init(name: "--arg1", isEnabled: true),
                .init(name: "--arg2", isEnabled: false),
            ]
        )
        let targetBUITests = Target.test(
            name: "BUITests",
            product: .uiTests,
            environmentVariables: [
                "a": EnvironmentVariable(value: "1", isEnabled: true),
                "b": EnvironmentVariable(value: "22", isEnabled: true),
                "d": EnvironmentVariable(value: "4", isEnabled: true),
            ],
            dependencies: [.target(name: "B")],
            launchArguments: [
                .init(name: "--arg1", isEnabled: true),
                .init(name: "--arg2", isEnabled: true),
            ]
        )
        let targetBIntegrationTests = Target.test(
            name: "BIntegrationTests",
            product: .unitTests,
            environmentVariables: [
                "c": EnvironmentVariable(value: "3", isEnabled: true),
                "e": EnvironmentVariable(value: "5", isEnabled: true),
            ],
            dependencies: [.target(name: "B")],
            launchArguments: [
                .init(name: "--arg1", isEnabled: true),
                .init(name: "--arg3", isEnabled: true),
            ]
        )
        let targetBSnapshotTests = Target.test(
            name: "BSnapshotTests",
            product: .unitTests,
            dependencies: [
                .target(name: "B"),
                .target(name: "A"),
            ]
        )
        let targetA = Target.test(
            name: "A",
            product: .framework,
            dependencies: [
                .target(name: "B"),
            ]
        )
        let targetADemo = Target.test(
            name: "ADemo",
            product: .app,
            environmentVariables: [
                "A": EnvironmentVariable(value: "B", isEnabled: true),
            ],
            dependencies: [
                .target(name: "B"),
            ]
        )
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )
        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "Project",
            targets: [
                targetA,
                targetADemo,
                targetATests,
                targetB,
                targetBTests,
                targetBUITests,
                targetBIntegrationTests,
                targetBSnapshotTests,
            ]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [
                .allProjects(
                    targetSchemesGrouping: .byNameSuffix(
                        build: [],
                        test: ["Tests", "UITests", "IntegrationTests", "SnapshotTests"],
                        run: ["Demo"]
                    ),
                    codeCoverageEnabled: false,
                    testingOptions: []
                ),
            ]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let expected = [
            makeScheme(
                name: "A",
                buildTargetNames: ["A", "ADemo"],
                testTargetNames: ["ATests"],
                runTargetName: "ADemo",
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false,
                runActionArguments: .init(
                    environmentVariables: ["A": EnvironmentVariable(value: "B", isEnabled: true)],
                    launchArguments: []
                )
            ),
            makeScheme(
                name: "B",
                buildTargetNames: ["B"],
                testTargetNames: ["BIntegrationTests", "BSnapshotTests", "BTests", "BUITests"],
                runTargetName: "B",
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false,
                testActionArguments: .init(
                    environmentVariables: [
                        "a": EnvironmentVariable(value: "1", isEnabled: true),
                        "b": EnvironmentVariable(value: "2", isEnabled: false),
                        "c": EnvironmentVariable(value: "3", isEnabled: true),
                        "d": EnvironmentVariable(value: "4", isEnabled: true),
                        "e": EnvironmentVariable(value: "5", isEnabled: true),
                    ],
                    launchArguments: [
                        .init(name: "--arg1", isEnabled: true),
                        .init(name: "--arg2", isEnabled: false),
                        .init(name: "--arg3", isEnabled: true),
                    ]
                )
            ),
        ]

        XCTAssertEqual(try XCTUnwrap(graph.projects[projectPath]).schemes, expected)
    }


    func test_map_projectSchemes_locale() async throws {
        // Given
        let subject = AutogeneratedSchemesProjectsGraphMapper()
        let targetA = Target.test(name: "A", product: .framework)
        let targetADemo = Target.test(name: "ADemo", product: .app)
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )
        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "Project",
            targets: [targetA, targetADemo, targetATests]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [
                .allProjects(
                    targetSchemesGrouping: .byNameSuffix(build: [], test: ["Tests"], run: ["Demo"]),
                    codeCoverageEnabled: false,
                    testingOptions: [],
                    testLanguage: "en",
                    testRegion: "US",
                    runLanguage: "cs",
                    runRegion: "CZ"
                ),
            ]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let expected = [
            makeScheme(
                name: "A",
                buildTargetNames: ["A", "ADemo"],
                testTargetNames: ["ATests"],
                runTargetName: "ADemo",
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false,
                testLanguage: "en",
                testRegion: "US",
                runActionOptions: .init(language: "cs", region: "CZ")
            ),
        ]

        XCTAssertEqual(try XCTUnwrap(graph.projects[projectPath]).schemes, expected)
    }

    func test_map_projectSchemes_screenCaptureFormat() async throws {
        // Given
        let subject = AutogeneratedSchemesProjectsGraphMapper()
        let targetA = Target.test(name: "A", product: .framework)
        let targetADemo = Target.test(name: "ADemo", product: .app)
        let targetATests = Target.test(
            name: "AUITests",
            product: .uiTests,
            dependencies: [.target(name: "A")]
        )
        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "Project",
            targets: [targetA, targetADemo, targetATests]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [
                .allProjects(
                    targetSchemesGrouping: .byNameSuffix(build: [], test: ["UITests"], run: ["Demo"]),
                    codeCoverageEnabled: false,
                    testingOptions: [],
                    testScreenCaptureFormat: .screenshots
                ),
            ]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let expected = [
            makeScheme(
                name: "A",
                buildTargetNames: ["A", "ADemo"],
                testTargetNames: ["AUITests"],
                runTargetName: "ADemo",
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false,
                testScreenCaptureFormat: .screenshots
            ),
        ]

        XCTAssertEqual(try XCTUnwrap(graph.projects[projectPath]).schemes, expected)
    }

    func test_map_projectSchemes_appExtension() async throws {
        // Given
        let subject = AutogeneratedSchemesProjectsGraphMapper()
        let targetB = Target.test(name: "B", product: .app)
        let targetBTests = Target.test(
            name: "BTests",
            product: .unitTests,
            dependencies: [
                .target(name: "B"),
                .target(name: "A"),
            ]
        )
        let targetBUITests = Target.test(
            name: "BUITests",
            product: .uiTests,
            dependencies: [.target(name: "B")]
        )
        let targetBIntegrationTests = Target.test(
            name: "BIntegrationTests",
            product: .unitTests,
            dependencies: [.target(name: "B")]
        )
        let targetBSnapshotTests = Target.test(
            name: "BSnapshotTests",
            product: .unitTests,
            dependencies: [
                .target(name: "B"),
                .target(name: "A"),
            ]
        )
        let targetAAppExtension = Target.test(
            name: "AAppExtension",
            product: .appExtension,
            dependencies: [
                .target(name: "B"),
            ]
        )
        let targetAMessagesExtension = Target.test(
            name: "AMessagesExtension",
            product: .messagesExtension,
            dependencies: [
                .target(name: "B"),
            ]
        )
        let targetA = Target.test(
            name: "A",
            product: .app,
            dependencies: [
                .target(name: "B"),
                .target(name: "AAppExtension"),
                .target(name: "AMessagesExtension"),
            ]
        )
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )
        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "Project",
            targets: [
                targetA,
                targetAAppExtension,
                targetAMessagesExtension,
                targetATests,
                targetB,
                targetBTests,
                targetBUITests,
                targetBIntegrationTests,
                targetBSnapshotTests,
            ]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [
                .allProjects(
                    targetSchemesGrouping: .byNameSuffix(
                        build: [],
                        test: ["Tests", "UITests", "IntegrationTests", "SnapshotTests"],
                        run: ["Demo"]
                    ),
                    codeCoverageEnabled: false,
                    testingOptions: []
                ),
            ]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let expected = [
            makeScheme(
                name: "A",
                buildTargetNames: ["A"],
                testTargetNames: ["ATests"],
                runTargetName: "A",
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false
            ),
            makeScheme(
                name: "AAppExtension",
                buildTargetNames: ["AAppExtension", "A"],
                testTargetNames: [],
                runTargetName: "A",
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false
            ),
            makeScheme(
                name: "AMessagesExtension",
                buildTargetNames: ["AMessagesExtension", "A"],
                testTargetNames: [],
                runTargetName: "A",
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false
            ),
            makeScheme(
                name: "B",
                buildTargetNames: ["B"],
                testTargetNames: ["BIntegrationTests", "BSnapshotTests", "BTests", "BUITests"],
                runTargetName: "B",
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false
            ),
        ]

        XCTAssertEqual(try XCTUnwrap(graph.projects[projectPath]).schemes, expected)
    }

    func test_map_projectSchemes_watch_extension() async throws {
        // Given
        let subject = AutogeneratedSchemesProjectsGraphMapper()
        let targetB = Target.test(name: "B", product: .app)
        let targetBTests = Target.test(
            name: "BTests",
            product: .unitTests,
            dependencies: [
                .target(name: "B"),
                .target(name: "AWatchApp"),
            ]
        )
        let targetBUITests = Target.test(
            name: "BUITests",
            product: .uiTests,
            dependencies: [.target(name: "B")]
        )
        let targetBIntegrationTests = Target.test(
            name: "BIntegrationTests",
            product: .unitTests,
            dependencies: [.target(name: "B")]
        )
        let targetBSnapshotTests = Target.test(
            name: "BSnapshotTests",
            product: .unitTests,
            dependencies: [
                .target(name: "B"),
                .target(name: "AWatchApp"),
            ]
        )
        let targetAWatchExtension = Target.test(
            name: "AWatchExtension",
            product: .watch2Extension,
            dependencies: [
                .target(name: "B"),
            ]
        )
        let targetAWatchApp = Target.test(
            name: "AWatchApp",
            product: .watch2App,
            dependencies: [
                .target(name: "AWatchExtension"),
            ]
        )
        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "Project",
            targets: [
                targetAWatchApp,
                targetAWatchExtension,
                targetB,
                targetBTests,
                targetBUITests,
                targetBIntegrationTests,
                targetBSnapshotTests,
            ]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [
                .allProjects(
                    targetSchemesGrouping: .byNameSuffix(
                        build: [],
                        test: ["Tests", "UITests", "IntegrationTests", "SnapshotTests"],
                        run: ["Demo"]
                    ),
                    codeCoverageEnabled: false,
                    testingOptions: []
                ),
            ]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let expected = [
            makeScheme(
                name: "AWatchApp",
                buildTargetNames: ["AWatchApp"],
                testTargetNames: [],
                runTargetName: "AWatchApp",
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false
            ),
            makeScheme(
                name: "AWatchExtension",
                buildTargetNames: ["AWatchExtension", "AWatchApp"],
                testTargetNames: [],
                runTargetName: "AWatchApp",
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false
            ),
            makeScheme(
                name: "B",
                buildTargetNames: ["B"],
                testTargetNames: ["BIntegrationTests", "BSnapshotTests", "BTests", "BUITests"],
                runTargetName: "B",
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false
            ),
        ]

        XCTAssertEqual(try XCTUnwrap(graph.projects[projectPath]).schemes, expected)
    }

    func test_map_projectSchemes_exceptRegexps() async throws {
        // Given
        let subject = AutogeneratedSchemesProjectsGraphMapper()
        let (targets, projectPath) = try makeProjectTargets()
        let project = Project.test(
            path: projectPath,
            name: "Project",
            targets: targets
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [
                .allProjects(
                    exceptRegexps: [".*Tests$"],
                    targetSchemesGrouping: .singleScheme,
                    codeCoverageEnabled: false,
                    testingOptions: []
                ),
            ]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        // Test targets matching `.*Tests$` are excluded, so no test targets remain.
        let expected = [
            makeScheme(
                name: "Project",
                buildTargetNames: ["A", "ADemo", "B"],
                testTargetNames: [],
                runTargetName: nil,
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false
            ),
        ]

        XCTAssertEqual(try XCTUnwrap(graph.projects[projectPath]).schemes, expected)
    }

    func test_map_projectSchemes_customProject_withoutAllProjects() async throws {
        // Given
        let subject = AutogeneratedSchemesProjectsGraphMapper()
        let (targets, projectPath) = try makeProjectTargets()
        let project = Project.test(
            path: projectPath,
            name: "Project",
            targets: targets
        )

        // Without an `.allProjects` config, a project schema will still be created for the specified project.
        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [
                .project(
                    name: "Project",
                    targetSchemesGrouping: .singleScheme,
                    codeCoverageEnabled: false,
                    testingOptions: []
                ),
            ]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let expected = [
            makeScheme(
                name: "Project",
                buildTargetNames: ["A", "ADemo", "B"],
                testTargetNames: ["ATests", "BIntegrationTests", "BSnapshotTests", "BTests", "BUITests"],
                runTargetName: nil,
                projectPath: projectPath,
                coverage: false,
                parallelizable: false,
                randomExecution: false
            ),
        ]
        XCTAssertEqual(try XCTUnwrap(graph.projects[projectPath]).schemes, expected)
    }

    func test_map_projectSchemes_customProject_onlyForMatchingProject() async throws {
        // Given
        let subject = AutogeneratedSchemesProjectsGraphMapper()
        let (targets, projectPath) = try makeProjectTargets()
        let project = Project.test(
            path: projectPath,
            name: "Project",
            targets: targets
        )

        let otherTarget = Target.test(name: "Other", product: .framework)
        let otherPath = try temporaryPath().appending(component: "OtherProject")
        let otherProject = Project.test(
            path: otherPath,
            name: "OtherProject",
            targets: [otherTarget]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path, otherPath],
            autogeneratedSchemes: [
                .allProjects(
                    targetSchemesGrouping: .singleScheme,
                    codeCoverageEnabled: false,
                    testingOptions: []
                ),
                .project(
                    name: "Project",
                    targetSchemesGrouping: .singleScheme,
                    codeCoverageEnabled: true,
                    testingOptions: []
                ),
            ]
        )

        var graph = Graph.test(
            workspace: workspace,
            projects: [project.path: project, otherPath: otherProject]
        )
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        // The non-matching project falls back to the `.allProjects` scheme (single framework target, no tests).
        let otherScheme = try XCTUnwrap(try XCTUnwrap(graph.projects[otherPath]).schemes.first)
        XCTAssertEqual(otherScheme.name, "OtherProject")
        XCTAssertEqual(
            otherScheme.buildAction?.targets,
            [TargetReference(projectPath: otherPath, name: otherTarget.name)]
        )
        XCTAssertNil(otherScheme.testAction)

        // The matching project uses the custom config (coverage enabled).
        let projectScheme = try XCTUnwrap(try XCTUnwrap(graph.projects[projectPath]).schemes.first)
        XCTAssertEqual(projectScheme.name, "Project")
        XCTAssertTrue(try XCTUnwrap(projectScheme.testAction?.coverage))
    }

    func test_map_projectSchemes_customProject_overridesAllProjects() async throws {
        // Given
        let subject = AutogeneratedSchemesProjectsGraphMapper()
        let (targets, projectPath) = try makeProjectTargets()
        let project = Project.test(
            path: projectPath,
            name: "Project",
            targets: targets
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [
                .allProjects(
                    targetSchemesGrouping: .singleScheme,
                    codeCoverageEnabled: false,
                    testingOptions: []
                ),
                .project(
                    name: "Project",
                    targetSchemesGrouping: .singleScheme,
                    codeCoverageEnabled: true,
                    testingOptions: []
                ),
            ]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        // The custom `.project` scheme replaces the identically-named `.allProjects` scheme,
        // so only the custom (coverage enabled) "Project" scheme remains.
        let schemes = try XCTUnwrap(graph.projects[projectPath]).schemes
        XCTAssertEqual(schemes.count, 1)
        let scheme = try XCTUnwrap(schemes.first)
        XCTAssertEqual(scheme.name, "Project")
        XCTAssertTrue(try XCTUnwrap(scheme.testAction?.coverage))
    }

    func test_map_workspaceScheme_and_projectSchemes_combined() async throws {
        // Given
        let subject = SequentialGraphMapper(
            [
                AutogeneratedSchemesWorkspaceGraphMapper(),
                AutogeneratedSchemesProjectsGraphMapper()
            ]
        )

        let targetA = Target.test(name: "A")
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )
        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [targetA, targetATests]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [
                .workspace(platform: .iOS),
                .allProjects(targetSchemesGrouping: .notGrouped),
            ]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        XCTAssertEqual(graph.workspace.schemes.count, 1)
        XCTAssertEqual(graph.workspace.schemes.first?.name, "A-Workspace")
        XCTAssertEqual(
            Set(try XCTUnwrap(graph.projects[projectPath]).schemes.map(\.name)),
            Set(["A", "ATests"])
        )
    }

    // MARK: - Helpers

    private func makeWorkspace(
        name: String = "A",
        projects: [AbsolutePath],
        autogeneratedSchemes: [AutogeneratedSchemes]
    ) -> Workspace {
        var generationOptions = Workspace.GenerationOptions.test()
        generationOptions.autogeneratedSchemes = autogeneratedSchemes
        return Workspace.test(name: name, projects: projects, generationOptions: generationOptions)
    }

    /// Creates the set of targets used by the project-level scheme tests (mirrors the project mapper tests).
    private func makeProjectTargets(
        includeAllIntegrationTests: Bool = false,
        runEnvironmentVariables: [String: EnvironmentVariable] = [:],
        runLaunchArguments: [LaunchArgument] = []
    ) throws -> ([Target], AbsolutePath) {
        let targetB = Target.test(
            name: "B",
            product: .app,
            launchArguments: runLaunchArguments
        )
        let targetBTests = Target.test(
            name: "BTests",
            product: .unitTests,
            dependencies: [
                .target(name: "B"),
                .target(name: "A"),
            ]
        )
        let targetBUITests = Target.test(
            name: "BUITests",
            product: .uiTests,
            dependencies: [.target(name: "B")]
        )
        let targetBIntegrationTests = Target.test(
            name: "BIntegrationTests",
            product: .unitTests,
            dependencies: [.target(name: "B")]
        )
        let targetBSnapshotTests = Target.test(
            name: "BSnapshotTests",
            product: .unitTests,
            dependencies: [
                .target(name: "B"),
                .target(name: "A"),
            ]
        )
        let targetA = Target.test(
            name: "A",
            product: .framework,
            dependencies: [
                .target(name: "B"),
            ]
        )
        let targetADemo = Target.test(
            name: "ADemo",
            product: .app,
            environmentVariables: runEnvironmentVariables,
            dependencies: [
                .target(name: "B"),
            ]
        )
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )
        var targets = [
            targetA,
            targetADemo,
            targetATests,
            targetB,
            targetBTests,
            targetBUITests,
            targetBIntegrationTests,
            targetBSnapshotTests,
        ]
        if includeAllIntegrationTests {
            targets.append(Target.test(
                name: "AllIntegrationTests",
                product: .unitTests,
                dependencies: [.target(name: "A"), .target(name: "B")]
            ))
        }

        return (targets, try temporaryPath())
    }

    private func makeScheme(
        name: String,
        buildTargetNames: [String],
        testTargetNames: [String] = [],
        runTargetName: String?,
        projectPath: AbsolutePath,
        coverage: Bool,
        parallelizable: Bool,
        randomExecution: Bool,
        runActionArguments: Arguments? = nil,
        testActionArguments: Arguments? = nil,
        testLanguage: String? = nil,
        testRegion: String? = nil,
        testScreenCaptureFormat: ScreenCaptureFormat? = nil,
        runActionOptions: RunActionOptions? = nil,
        testAction: TestAction? = nil
    ) -> Scheme {
        let defaultTestAction = testTargetNames.isEmpty ? nil : TestAction.test(
            targets: testTargetNames.map {
                TestableTarget(
                    target: TargetReference(projectPath: projectPath, name: $0),
                    parallelizable: parallelizable,
                    randomExecutionOrdering: randomExecution
                )
            },
            arguments: testActionArguments,
            coverage: coverage,
            language: testLanguage,
            region: testRegion,
            preferredScreenCaptureFormat: testScreenCaptureFormat
        )

        return Scheme(
            name: name,
            shared: true,
            buildAction: buildTargetNames.isEmpty ? nil : BuildAction(
                targets: buildTargetNames.map { TargetReference(projectPath: projectPath, name: $0) }
            ),
            testAction: testAction ?? defaultTestAction,
            runAction: runTargetName.map {
                RunAction.test(
                    executable: TargetReference(projectPath: projectPath, name: $0),
                    arguments: runActionArguments,
                    options: runActionOptions ?? .init()
                )
            }
        )
    }
}
