import Foundation
import GekoGraph
import GekoGraphTesting
import ProjectDescription
import XCTest
import GekoCore

@testable import GekoGenerator
@testable import GekoSupportTesting

final class AutogeneratedSchemesWorkspaceGraphMapperTests: GekoUnitTestCase {
    func test_map_workspaceScheme() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A")
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )

        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [
                targetA,
                targetATests,
            ]
        )

        let targetB = Target.test(name: "B")
        let targetBTests = Target.test(
            name: "BTests",
            product: .unitTests,
            dependencies: [.target(name: "B")]
        )

        let projectBPath = try temporaryPath().appending(component: "ProjectB")
        let projectB = Project.test(
            path: projectBPath,
            name: "ProjectB",
            targets: [
                targetB,
                targetBTests,
            ]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path, projectB.path],
            autogeneratedSchemes: [.workspace(platform: .iOS)]
        )

        var graph = Graph.test(
            workspace: workspace,
            projects: [project.path: project, projectB.path: projectB]
        )
        var sideTable = GraphSideTable()

        // When
        let sideEffects = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        XCTAssertEmpty(sideEffects)
        let schemes = graph.workspace.schemes

        XCTAssertEqual(schemes.count, 1)
        let scheme = try XCTUnwrap(schemes.first)
        XCTAssertTrue(scheme.shared)
        XCTAssertEqual(scheme.name, "A-Workspace")
        XCTAssertEqual(
            Set(scheme.buildAction.map(\.targets) ?? []),
            Set([
                TargetReference(projectPath: projectBPath, name: targetB.name),
                TargetReference(projectPath: projectPath, name: targetA.name),
            ])
        )
        XCTAssertEqual(
            Set(scheme.testAction.map(\.targets) ?? []),
            Set([
                TestableTarget(
                    target: TargetReference(projectPath: projectPath, name: targetATests.name),
                    parallelizable: false
                ),
                TestableTarget(
                    target: TargetReference(projectPath: projectBPath, name: targetBTests.name),
                    parallelizable: false
                ),
            ])
        )
        XCTAssertFalse(try XCTUnwrap(scheme.testAction?.coverage))
    }

    func test_map_workspaceScheme_disabled() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A")
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )

        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [
                targetA,
                targetATests,
            ]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: []
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        XCTAssertEqual(graph.workspace.schemes, [])
    }

    func test_map_workspaceScheme_multiple_project_sorting() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A")
        let targetB = Target.test(name: "B")
        let targetC = Target.test(name: "C")

        let projectB = Project.test(
            path: try temporaryPath().appending(component: "ProjectB"),
            name: "ProjectB",
            targets: [
                targetB,
            ]
        )

        let projectA = Project.test(
            path: try temporaryPath().appending(component: "ProjectA"),
            name: "ProjectA",
            targets: [
                targetA,
                targetC,
            ]
        )

        let workspace = makeWorkspace(projects: [projectA.path, projectB.path], autogeneratedSchemes: [.workspace(platform: .iOS)])
        var graph = Graph.test(workspace: workspace, projects: [projectA.path: projectA, projectB.path: projectB])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let scheme = try XCTUnwrap(graph.workspace.schemes.first)
        let targetsNames = scheme.buildAction?.targets.map(\.name)
        XCTAssertEqual(targetsNames, ["A", "B", "C"])
    }

    func test_map_workspaceScheme_multiplePlatforms() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A", platform: .iOS)
        let targetATests = Target.test(
            name: "ATests",
            platform: .iOS,
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )

        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [
                targetA,
                targetATests,
            ]
        )

        let targetB = Target.test(name: "B", platform: .macOS)
        let targetBTests = Target.test(
            name: "BTests",
            platform: .macOS,
            product: .unitTests,
            dependencies: [.target(name: "B")]
        )

        let projectBPath = try temporaryPath().appending(component: "ProjectB")
        let projectB = Project.test(
            path: projectBPath,
            name: "ProjectB",
            targets: [
                targetB,
                targetBTests,
            ]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path, projectB.path],
            autogeneratedSchemes: [
                .workspace(platform: .iOS, suffix: "iOS"),
                .workspace(platform: .macOS, suffix: "macOS"),
            ]
        )

        var graph = Graph.test(
            workspace: workspace,
            projects: [project.path: project, projectB.path: projectB]
        )
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let schemes = graph.workspace.schemes
        XCTAssertEqual(schemes.count, 2)
        XCTAssertEqual(
            schemes.map(\.name),
            ["A-Workspace-iOS", "A-Workspace-macOS"]
        )
        let iosScheme = try XCTUnwrap(schemes.first(where: { $0.name == "A-Workspace-iOS" }))
        let macOSScheme = try XCTUnwrap(schemes.first(where: { $0.name == "A-Workspace-macOS" }))
        XCTAssertEqual(
            iosScheme.buildAction.map(\.targets) ?? [],
            [
                TargetReference(projectPath: projectPath, name: targetA.name),
            ]
        )
        XCTAssertEqual(
            macOSScheme.buildAction.map(\.targets) ?? [],
            [
                TargetReference(projectPath: projectBPath, name: targetB.name),
            ]
        )
        XCTAssertEqual(
            iosScheme.testAction.map(\.targets) ?? [],
            [
                TestableTarget(
                    target: TargetReference(projectPath: projectPath, name: targetATests.name),
                    parallelizable: false
                ),
            ]
        )
        XCTAssertEqual(
            macOSScheme.testAction.map(\.targets) ?? [],
            [
                TestableTarget(
                    target: TargetReference(projectPath: projectBPath, name: targetBTests.name),
                    parallelizable: false
                ),
            ]
        )
    }

    func test_map_workspaceScheme_multiplePlatforms_suffixNotSpecified() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A", platform: .iOS)
        let targetATests = Target.test(
            name: "ATests",
            platform: .iOS,
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )

        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [
                targetA,
                targetATests,
            ]
        )

        let targetB = Target.test(name: "B", platform: .macOS)
        let targetBTests = Target.test(
            name: "BTests",
            platform: .macOS,
            product: .unitTests,
            dependencies: [.target(name: "B")]
        )

        let projectBPath = try temporaryPath().appending(component: "ProjectB")
        let projectB = Project.test(
            path: projectBPath,
            name: "ProjectB",
            targets: [
                targetB,
                targetBTests,
            ]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path, projectB.path],
            autogeneratedSchemes: [
                .workspace(platform: .iOS),
                .workspace(platform: .macOS),
            ]
        )

        var graph = Graph.test(
            workspace: workspace,
            projects: [project.path: project, projectB.path: projectB]
        )
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let schemes = graph.workspace.schemes
        XCTAssertEqual(schemes.count, 1)
        XCTAssertEqual(
            schemes.map(\.name),
            ["A-Workspace"]
        )
        let iosScheme = try XCTUnwrap(schemes.first(where: { $0.name == "A-Workspace" }))
        XCTAssertEqual(
            iosScheme.buildAction.map(\.targets) ?? [],
            [
                TargetReference(projectPath: projectPath, name: targetA.name),
            ]
        )
        XCTAssertEqual(
            iosScheme.testAction.map(\.targets) ?? [],
            [
                TestableTarget(
                    target: TargetReference(projectPath: projectPath, name: targetATests.name),
                    parallelizable: false
                ),
            ]
        )
    }

    func test_map_workspaceScheme_suffix() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A")
        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [targetA]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [.workspace(platform: .iOS, suffix: "All")]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let scheme = try XCTUnwrap(graph.workspace.schemes.first)
        XCTAssertEqual(scheme.name, "A-Workspace-All")
    }

    func test_map_workspaceScheme_onlyFocusedTargets() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A")
        let targetB = Target.test(name: "B")
        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [targetA, targetB]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [.workspace(platform: .iOS, onlyFocusedTargets: true)]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()
        sideTable.workspace.focusedTargets = [targetA.name]

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let scheme = try XCTUnwrap(graph.workspace.schemes.first)
        XCTAssertEqual(
            scheme.buildAction.map(\.targets) ?? [],
            [TargetReference(projectPath: projectPath, name: targetA.name)]
        )
    }

    func test_map_workspaceScheme_codeCoverage_disabled() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A")
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )
        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [targetA, targetATests]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [.workspace(platform: .iOS, codeCoverageMode: .disabled)]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let scheme = try XCTUnwrap(graph.workspace.schemes.first)
        XCTAssertFalse(try XCTUnwrap(scheme.testAction?.coverage))
    }

    func test_map_workspaceScheme_codeCoverage_all() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A")
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )
        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [targetA, targetATests]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [.workspace(platform: .iOS, codeCoverageMode: .all, testingOptions: [])]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let scheme = try XCTUnwrap(graph.workspace.schemes.first)
        XCTAssertTrue(try XCTUnwrap(scheme.testAction?.coverage))
    }

    func test_map_workspaceScheme_codeCoverage_targets() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A")
        let targetB = Target.test(name: "B")
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )
        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [targetA, targetB, targetATests]
        )

        let targetBRef = TargetReference(projectPath: projectPath, name: "B")
        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [.workspace(platform: .iOS, codeCoverageMode: .targets([targetBRef]), testingOptions: [])]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let scheme = try XCTUnwrap(graph.workspace.schemes.first)
        let testAction = try XCTUnwrap(scheme.testAction)
        XCTAssertTrue(testAction.coverage)
        XCTAssertEqual(testAction.codeCoverageTargets, [targetBRef])
    }

    func test_map_workspaceScheme_codeCoverage_relevant_nonEmpty() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A")
        let targetB = Target.test(name: "B")
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )
        let projectPath = try temporaryPath()
        let targetBRef = TargetReference(projectPath: projectPath, name: "B")
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [targetA, targetB, targetATests],
            schemes: [
                Scheme.test(
                    name: "B",
                    testAction: TestAction.test(coverage: true, codeCoverageTargets: [targetBRef])
                ),
            ]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [.workspace(platform: .iOS, codeCoverageMode: .relevant)]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let scheme = try XCTUnwrap(graph.workspace.schemes.first)
        let testAction = try XCTUnwrap(scheme.testAction)
        XCTAssertTrue(testAction.coverage)
        XCTAssertEqual(testAction.codeCoverageTargets, [targetBRef])
    }

    func test_map_workspaceScheme_testingOptions() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A")
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )
        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [targetA, targetATests]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [.workspace(platform: .iOS, testingOptions: [.parallelizable, .randomExecutionOrdering])]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let scheme = try XCTUnwrap(graph.workspace.schemes.first)
        XCTAssertEqual(
            scheme.testAction.map(\.targets) ?? [],
            [
                TestableTarget(
                    target: TargetReference(projectPath: projectPath, name: targetATests.name),
                    parallelizable: true,
                    randomExecutionOrdering: true
                ),
            ]
        )
    }

    func test_map_workspaceScheme_language_region() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A")
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )
        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [targetA, targetATests]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [.workspace(platform: .iOS, testLanguage: "cs", testRegion: "CZ")]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let scheme = try XCTUnwrap(graph.workspace.schemes.first)
        XCTAssertEqual(try XCTUnwrap(scheme.testAction?.language), "cs")
        XCTAssertEqual(try XCTUnwrap(scheme.testAction?.region), "CZ")
    }

    func test_map_workspaceScheme_screenCaptureFormat() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A")
        let targetATests = Target.test(
            name: "AUITests",
            product: .uiTests,
            dependencies: [.target(name: "A")]
        )
        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [targetA, targetATests]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [.workspace(platform: .iOS, testScreenCaptureFormat: .screenshots)]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let scheme = try XCTUnwrap(graph.workspace.schemes.first)
        XCTAssertEqual(try XCTUnwrap(scheme.testAction?.preferredScreenCaptureFormat), .screenshots)
    }

    func test_map_workspaceScheme_codeCoverageMode_relevant_complex() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A")
        let targetB = Target.test(name: "B")
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )

        let projectAPath = try temporaryPath()
        let targetBRef = TargetReference(projectPath: projectAPath, name: "B")
        let projectSingleCoverage = Project.test(
            path: projectAPath,
            name: "ProjectA",
            targets: [
                targetA,
                targetB,
                targetATests,
            ],
            schemes: [
                Scheme.test(
                    name: "B",
                    testAction: TestAction.test(
                        coverage: true,
                        codeCoverageTargets: [targetBRef]
                    )
                ),
            ]
        )

        let projectBPath = try temporaryPath().appending(component: "ProjectB")
        let targetCRef = TargetReference(projectPath: projectBPath, name: "C")
        let targetDRef = TargetReference(projectPath: projectBPath, name: "D")
        let projectAllCoverage = Project.test(
            path: projectBPath,
            name: "ProjectB",
            targets: [
                Target.test(name: "C"),
                Target.test(name: "D"),
            ],
            schemes: [
                Scheme.test(
                    buildAction: BuildAction.test(targets: [targetCRef, targetDRef]),
                    testAction: TestAction.test(coverage: true)
                ),
            ]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [projectAPath, projectBPath],
            autogeneratedSchemes: [.workspace(platform: .iOS, codeCoverageMode: .relevant)]
        )

        var graph = Graph.test(
            workspace: workspace,
            projects: [projectAPath: projectSingleCoverage, projectBPath: projectAllCoverage]
        )
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let scheme = try XCTUnwrap(graph.workspace.schemes.first)
        let testAction = try XCTUnwrap(scheme.testAction)

        XCTAssertTrue(testAction.coverage)
        XCTAssertEqual(testAction.codeCoverageTargets.count, 3)
        XCTAssertEqual(Set(testAction.codeCoverageTargets), Set([targetBRef, targetCRef, targetDRef]))
    }

    func test_map_workspaceScheme_codeCoverageMode_relevant_empty() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A")
        let targetB = Target.test(name: "B")
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )

        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [
                targetA,
                targetB,
                targetATests,
            ],
            schemes: []
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path],
            autogeneratedSchemes: [.workspace(platform: .iOS, codeCoverageMode: .relevant)]
        )

        var graph = Graph.test(workspace: workspace, projects: [project.path: project])
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let scheme = try XCTUnwrap(graph.workspace.schemes.first)
        let testAction = try XCTUnwrap(scheme.testAction)

        XCTAssertFalse(testAction.coverage)
        XCTAssertEmpty(testAction.codeCoverageTargets)
    }

    func test_map_workspaceScheme_testing_options_all() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A")
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )

        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [
                targetA,
                targetATests,
            ]
        )

        let targetB = Target.test(name: "B")
        let targetBTests = Target.test(
            name: "BTests",
            product: .unitTests,
            dependencies: [.target(name: "B")]
        )

        let projectBPath = try temporaryPath().appending(component: "ProjectB")
        let projectB = Project.test(
            path: projectBPath,
            name: "ProjectB",
            targets: [
                targetB,
                targetBTests,
            ]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path, projectB.path],
            autogeneratedSchemes: [
                .workspace(platform: .iOS, codeCoverageMode: .disabled, testingOptions: [.parallelizable, .randomExecutionOrdering]),
            ]
        )

        var graph = Graph.test(
            workspace: workspace,
            projects: [project.path: project, projectB.path: projectB]
        )
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let schemes = graph.workspace.schemes
        XCTAssertEqual(schemes.count, 1)
        let scheme = try XCTUnwrap(schemes.first)
        XCTAssertTrue(scheme.shared)
        XCTAssertEqual(scheme.name, "A-Workspace")
        // The workspace build action only contains non-test targets.
        XCTAssertEqual(
            Set(scheme.buildAction.map(\.targets) ?? []),
            Set([
                TargetReference(projectPath: projectBPath, name: targetB.name),
                TargetReference(projectPath: projectPath, name: targetA.name),
            ])
        )
        XCTAssertEqual(
            Set(scheme.testAction.map(\.targets) ?? []),
            Set([
                TestableTarget(
                    target: TargetReference(projectPath: projectPath, name: targetATests.name),
                    parallelizable: true,
                    randomExecutionOrdering: true
                ),
                TestableTarget(
                    target: TargetReference(projectPath: projectBPath, name: targetBTests.name),
                    parallelizable: true,
                    randomExecutionOrdering: true
                ),
            ])
        )
        XCTAssertFalse(try XCTUnwrap(scheme.testAction?.coverage))
    }

    func test_map_workspaceScheme_testing_options_single_value() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A")
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )

        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [
                targetA,
                targetATests,
            ]
        )

        let targetB = Target.test(name: "B")
        let targetBTests = Target.test(
            name: "BTests",
            product: .unitTests,
            dependencies: [.target(name: "B")]
        )

        let projectBPath = try temporaryPath().appending(component: "ProjectB")
        let projectB = Project.test(
            path: projectBPath,
            name: "ProjectB",
            targets: [
                targetB,
                targetBTests,
            ]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path, projectB.path],
            autogeneratedSchemes: [
                .workspace(platform: .iOS, codeCoverageMode: .disabled, testingOptions: [.parallelizable]),
            ]
        )

        var graph = Graph.test(
            workspace: workspace,
            projects: [project.path: project, projectB.path: projectB]
        )
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let schemes = graph.workspace.schemes
        XCTAssertEqual(schemes.count, 1)

        let scheme = try XCTUnwrap(schemes.first)
        XCTAssertTrue(scheme.shared)
        XCTAssertEqual(scheme.name, "A-Workspace")
        XCTAssertEqual(
            Set(scheme.buildAction.map(\.targets) ?? []),
            Set([
                TargetReference(
                    projectPath: projectBPath,
                    name: targetB.name
                ),
                TargetReference(
                    projectPath: projectPath,
                    name: targetA.name
                ),
            ])
        )
        XCTAssertEqual(
            Set(scheme.testAction.map(\.targets) ?? []),
            Set([
                TestableTarget(
                    target: TargetReference(projectPath: projectPath, name: targetATests.name),
                    parallelizable: true,
                    randomExecutionOrdering: false
                ),
                TestableTarget(
                    target: TargetReference(projectPath: projectBPath, name: targetBTests.name),
                    parallelizable: true,
                    randomExecutionOrdering: false
                ),
            ])
        )
    }

    func test_map_workspaceScheme_testing_options_empty() async throws {
        // Given
        let subject = AutogeneratedSchemesWorkspaceGraphMapper()
        let targetA = Target.test(name: "A")
        let targetATests = Target.test(
            name: "ATests",
            product: .unitTests,
            dependencies: [.target(name: "A")]
        )

        let projectPath = try temporaryPath()
        let project = Project.test(
            path: projectPath,
            name: "ProjectA",
            targets: [
                targetA,
                targetATests,
            ]
        )

        let targetB = Target.test(name: "B")
        let targetBTests = Target.test(
            name: "BTests",
            product: .unitTests,
            dependencies: [.target(name: "B")]
        )

        let projectBPath = try temporaryPath().appending(component: "ProjectB")
        let projectB = Project.test(
            path: projectBPath,
            name: "ProjectB",
            targets: [
                targetB,
                targetBTests,
            ]
        )

        let workspace = makeWorkspace(
            name: "A",
            projects: [project.path, projectB.path],
            autogeneratedSchemes: [
                .workspace(platform: .iOS, codeCoverageMode: .disabled, testingOptions: []),
            ]
        )

        var graph = Graph.test(
            workspace: workspace,
            projects: [project.path: project, projectB.path: projectB]
        )
        var sideTable = GraphSideTable()

        // When
        _ = try await subject.map(graph: &graph, sideTable: &sideTable)

        // Then
        let schemes = graph.workspace.schemes

        XCTAssertEqual(schemes.count, 1)
        let scheme = try XCTUnwrap(schemes.first)
        XCTAssertTrue(scheme.shared)
        XCTAssertEqual(scheme.name, "A-Workspace")
        XCTAssertEqual(
            Set(scheme.buildAction.map(\.targets) ?? []),
            Set([
                TargetReference(
                    projectPath: projectBPath,
                    name: targetB.name
                ),
                TargetReference(
                    projectPath: projectPath,
                    name: targetA.name
                ),
            ])
        )
        XCTAssertEqual(
            Set(scheme.testAction.map(\.targets) ?? []),
            Set([
                TestableTarget(
                    target: TargetReference(projectPath: projectPath, name: targetATests.name),
                    parallelizable: false,
                    randomExecutionOrdering: false
                ),
                TestableTarget(
                    target: TargetReference(projectPath: projectBPath, name: targetBTests.name),
                    parallelizable: false,
                    randomExecutionOrdering: false
                ),
            ])
        )
        XCTAssertFalse(try XCTUnwrap(scheme.testAction?.coverage))
    }

    // MARK: - Helpers

    private func makeWorkspace(
        name: String = "A",
        projects: [AbsolutePath],
        autogeneratedSchemes: [AutogeneratedSchemes]
    ) -> Workspace {
        var generationOptions = Workspace.GenerationOptions.test()
        generationOptions.autogeneratedSchemes = autogeneratedSchemes
        return Workspace.test(name: name, projects: projects, generationOptions: generationOptions)
    }
}
