import Foundation
import GekoCore
import GekoGraph
import ProjectDescription
import GekoSupport

/// Disables deprecated `project.options.automaticSchemesOptions` if `generationOptions.autogeneratedSchemes` is used.
public final class AutogeneratedSchemesProjectMapperConfigurator: WorkspaceMapping {

    public init() {}

    public func map(
        workspace: inout WorkspaceWithProjects,
        sideTable: inout WorkspaceSideTable
    ) throws -> [SideEffectDescriptor] {

        if !workspace.workspace.allProjectsAutogeneratedSchemes.isEmpty || !workspace.workspace.customProjectsAutogeneratedSchemes.isEmpty {
            workspace.projects = workspace.projects.map {
                var project = $0
                project.options.automaticSchemesOptions = .disabled
                return project
            }
        }

        return []
    }
}
