import Foundation
import GekoCore
import GekoGraph
import GekoSupport
import ProjectDescription
import GekoLoader

public final class AutogeneratedTestPlansGraphMapper: GraphMapping {

    // MARK: - Init

    public init() {}

    // MARK: - GraphMapping

    public func map(
        graph: inout Graph,
        sideTable: inout GraphSideTable
    ) async throws -> [SideEffectDescriptor] {
        let generatorPaths = GeneratorPaths(manifestDirectory: graph.workspace.path)

        graph.projects = try Dictionary(uniqueKeysWithValues: graph.projects.map { projectPath, project in
            var project = project

            try mapProjectSchemes(
                project: &project,
                generatorPaths: generatorPaths,
                autogeneratedTestPlans: graph.workspace.generationOptions.autogeneratedTestPlans
            )

            return (projectPath, project)
        })

        return []
    }

    public func mapProjectSchemes(
        project: inout Project,
        generatorPaths: GeneratorPaths,
        autogeneratedTestPlans: [AutogeneratedTestPlan],
    ) throws {
        for autogeneratedTestPlan in autogeneratedTestPlans {
            guard
                let schemeReference = autogeneratedTestPlan.scheme,
                project.name == schemeReference.project
            else {
                continue
            }

            project.schemes = try project.schemes.map { scheme in
                var scheme = scheme
                guard scheme.name == schemeReference.scheme else {
                    return scheme
                }

                let path = try autogeneratedTestPlan.resolvePath(generatorPaths: generatorPaths)

                if var testAction = scheme.testAction {
                    var testPlans = testAction.testPlans ?? []
                    let testPlan = TestPlan(
                        path: path,
                        testTargets: [],
                        isDefault: false
                    )
                    testPlans.append(testPlan)
                    testAction.testPlans = testPlans
                    scheme.testAction = testAction
                } else {
                    scheme.testAction = .testPlans([path])
                }
                return scheme
            }
        }
    }
}
