import Foundation
import GekoCore
import GekoGraph
import GekoSupport
import ProjectDescription
import GekoLoader

public final class AutogeneratedSchemesWorkspaceGraphMapper: GraphMapping {

    public init() {}

    public func map(
        graph: inout Graph,
        sideTable: inout GraphSideTable
    ) async throws -> [SideEffectDescriptor] {
        if let project = graph.projects.first?.value {
            let schemes: [Scheme]

            if graph.workspace.generationOptions.autogeneratedSchemes.isEmpty {
                schemes = []
            } else {
                schemes = graph.workspace.autogeneratedSchemeWorkspaces.map { autogeneratedSchemeWorkspace in
                    workspaceScheme(
                        autogeneratedSchemeWorkspace: autogeneratedSchemeWorkspace,
                        project: project,
                        workspace: graph.workspace,
                        projects: graph.projects.map(\.value),
                        focusedTargets: sideTable.workspace.focusedTargets
                    )
                }
            }

            graph.workspace.schemes.append(contentsOf: schemes.uniqued(by: \.name))
        }
        return []
    }

    // MARK: - Private

    private func workspaceScheme(
        autogeneratedSchemeWorkspace: AutogeneratedSchemes.AutogeneratedSchemeWorkspace,
        project: Project,
        workspace: Workspace,
        projects: [Project],
        focusedTargets: Set<String>
    ) -> Scheme {
        let testingOptions = autogeneratedSchemeWorkspace.testingOptions
        var (targets, testableTargets): ([TargetReference], [TestableTarget]) = projects
            .reduce(([], [])) { result, project in
                let targets = project.targets
                    .filter { $0.supports(autogeneratedSchemeWorkspace.platform) }
                    .filter { !$0.product.testsBundle }
                    .filter {
                        guard
                            autogeneratedSchemeWorkspace.onlyFocusedTargets,
                            !focusedTargets.isEmpty
                        else { return true }
                        return focusedTargets.contains($0.name)
                    }
                    .filter {
                        guard !autogeneratedSchemeWorkspace.productFilters.isEmpty else { return true }
                        return autogeneratedSchemeWorkspace.productFilters.contains($0.product)
                    }
                    .map { TargetReference(projectPath: project.path, name: $0.name) }

                let testableTargets = project.targets
                    .filter { $0.supports(autogeneratedSchemeWorkspace.platform) }
                    .filter(\.product.testsBundle)
                    .filter {
                        guard
                            autogeneratedSchemeWorkspace.onlyFocusedTargets,
                            !focusedTargets.isEmpty
                        else { return true }
                        return focusedTargets.contains($0.name)
                    }
                    .filter {
                        guard !autogeneratedSchemeWorkspace.productFilters.isEmpty else { return true }
                        return autogeneratedSchemeWorkspace.productFilters.contains($0.product)
                    }
                    .map { TargetReference(projectPath: project.path, name: $0.name) }
                    .map {
                        TestableTarget(
                            target: $0,
                            parallelizable: testingOptions.contains(.parallelizable),
                            randomExecutionOrdering: testingOptions.contains(.randomExecutionOrdering)
                        )
                    }

                return (result.0 + targets, result.1 + testableTargets)
            }

        targets = targets.sorted(by: { $0.name < $1.name })
        testableTargets = testableTargets.sorted(by: { $0.target.name < $1.target.name })

        let coverageSettings = codeCoverageSettings(workspace: workspace, autogeneratedSchemeWorkspace: autogeneratedSchemeWorkspace, projects: projects)

        let schemeName: String
        if let suffix = autogeneratedSchemeWorkspace.suffix {
            schemeName = "\(workspace.name)-Workspace-\(suffix)"
        } else {
            schemeName = "\(workspace.name)-Workspace"
        }

        return Scheme(
            name: schemeName,
            shared: true,
            buildAction: BuildAction(targets: targets),
            testAction: TestAction(
                targets: testableTargets,
                arguments: autogeneratedSchemeWorkspace.testActionArguments,
                configurationName: project.defaultDebugBuildConfigurationName,
                attachDebugger: true,
                coverage: coverageSettings.isEnabled,
                codeCoverageTargets: coverageSettings.targets,
                expandVariableFromTarget: nil,
                preActions: [],
                postActions: [],
                diagnosticsOptions: .init(),
                language: autogeneratedSchemeWorkspace.testLanguage?.identifier,
                region: autogeneratedSchemeWorkspace.testRegion,
                preferredScreenCaptureFormat: autogeneratedSchemeWorkspace.testScreenCaptureFormat
            )
        )
    }

    private func codeCoverageSettings(workspace: Workspace, autogeneratedSchemeWorkspace: AutogeneratedSchemes.AutogeneratedSchemeWorkspace, projects: [Project]) -> (isEnabled: Bool, targets: [TargetReference]) {
        let codeCoverageTargets = workspace.codeCoverageTargets(autogeneratedSchemeWorkspace: autogeneratedSchemeWorkspace, projects: projects)

        switch autogeneratedSchemeWorkspace.codeCoverageMode {
        case .all: return (true, codeCoverageTargets)
        case .disabled: return (false, codeCoverageTargets)
        case .targets: return (true, codeCoverageTargets)
        case .relevant:
            return (!codeCoverageTargets.isEmpty, codeCoverageTargets)
        }
    }
}
