import Foundation
import GekoCore
import GekoGraph
import GekoSupport
import ProjectDescription
import GekoLoader

public final class AutogeneratedSchemesProjectsGraphMapper: GraphMapping {
    // swiftlint:disable:this type_body_length
    // MARK: - Init

    public init() {}

    // MARK: - GraphMapping

    public func map(
        graph: inout Graph,
        sideTable: inout GraphSideTable
    ) async throws -> [SideEffectDescriptor] {

        let allProjectsAutogeneratedSchemes = graph.workspace.allProjectsAutogeneratedSchemes
        let customProjectsAutogeneratedSchemes = graph.workspace.customProjectsAutogeneratedSchemes

        graph.projects = try Dictionary(uniqueKeysWithValues: graph.projects.map { projectPath, project in
            var project = project

            let userDefinedSchemes = project.schemes
            let userDefinedSchemeNames = Set(project.schemes.map(\.name))

            var allProjectsSchemes = try mapAllProjectSchemes(project: &project, sideTable: &sideTable, allProjectsAutogeneratedSchemes: allProjectsAutogeneratedSchemes)

            let customProjectSchemes: [Scheme]
            let customProjectSchemesNames: Set<String>
            if let customAutogeneratedSchemeProject = customProjectsAutogeneratedSchemes.first(where: { $0.projectName == project.name })?.autogeneratedSchemeProject {
                customProjectSchemes = try projectSchemes(
                    project: &project,
                    focusedTargets: sideTable.workspace.focusedTargets,
                    autogeneratedSchemeProject: customAutogeneratedSchemeProject
                )
                customProjectSchemesNames = Set(customProjectSchemes.map(\.name))
            } else {
                customProjectSchemes = []
                customProjectSchemesNames = []
            }

            allProjectsSchemes = allProjectsSchemes.filter { !customProjectSchemesNames.contains($0.name) }

            let autogeneratedSchemes = allProjectsSchemes + customProjectSchemes

            let filteredAutogeneratedSchemes = autogeneratedSchemes.filter { !userDefinedSchemeNames.contains($0.name) }
            project.schemes = (userDefinedSchemes + filteredAutogeneratedSchemes).sorted { $0.name < $1.name }

            return (projectPath, project)
        })

        return []
    }

    // MARK: - Private

    // swiftlint:disable:next function_body_length
    private func projectSchemes(
        project: inout Project,
        focusedTargets: Set<String>,
        autogeneratedSchemeProject: AutogeneratedSchemes.AutogeneratedSchemeProject
    ) throws -> [Scheme] {
        let exceptRegexps = try autogeneratedSchemeProject.exceptRegexps.map { try Regex($0) }

        var buildTargets: Set<Target> = []
        var testTargets: Set<Target> = []
        var runTargets: Set<Target> = []

        targetsLoop: for target in project.targets {

            if autogeneratedSchemeProject.onlyFocusedTargets,
               !focusedTargets.isEmpty,
               !focusedTargets.contains(target.name) {
                continue
            }

            for exceptRegexp in exceptRegexps {
                if try exceptRegexp.wholeMatch(in: target.name) != nil {
                    continue targetsLoop
                }
            }

            switch target.product {
            case .app, .appClip, .commandLineTool, .watch2App, .xpc:
                runTargets.insert(target)
            case .uiTests, .unitTests:
                testTargets.insert(target)
            case .framework, .staticLibrary, .dynamicLibrary, .staticFramework, .bundle, .appExtension, .watch2Extension,
                 .tvTopShelfExtension, .messagesExtension, .stickerPackExtension, .systemExtension, .extensionKitExtension,
                 .macro, .aggregateTarget:
                buildTargets.insert(target)
            }
        }

        // swiftlint:disable:next large_tuple
        let targetGroups: [String: (build: Set<Target>, test: Set<Target>, run: Set<Target>)]
        switch autogeneratedSchemeProject.targetSchemesGrouping {
        case .singleScheme:
            targetGroups = [
                project.name: (
                    build: buildTargets,
                    test: testTargets,
                    run: runTargets
                ),
            ]
        case let .byNameSuffix(buildSuffixes, testSuffixes, runSuffixes):
            targetGroups = groupByName(
                buildTargets: &buildTargets,
                testTargets: &testTargets,
                runTargets: &runTargets,
                buildSuffixes: buildSuffixes,
                testSuffixes: testSuffixes,
                runSuffixes: runSuffixes
            )
        case .pods:
            let schemes = createPodSchemes(
                autogeneratedSchemeProject: autogeneratedSchemeProject,
                project: project,
                buildTargets: buildTargets,
                testTargets: testTargets,
                runTargets: runTargets,
                buildConfiguration: project.defaultDebugBuildConfigurationName
            )
            return schemes.sorted { $0.name < $1.name }
        case .notGrouped:
            targetGroups = [:]
        }

        let autogeneratedSchemes: [Scheme]
        if !targetGroups.isEmpty {
            autogeneratedSchemes = targetGroups.map { name, targets in
                createDefaultScheme(
                    name: name,
                    autogeneratedSchemeProject: autogeneratedSchemeProject,
                    project: project,
                    buildTargets: targets.build,
                    testTargets: targets.test,
                    runTargets: targets.run,
                    buildConfiguration: project.defaultDebugBuildConfigurationName
                )
            }
        } else {
            let remainingBuildTargetsSchemes = buildTargets.map {
                createDefaultScheme(
                    name: $0.name,
                    autogeneratedSchemeProject: autogeneratedSchemeProject,
                    project: project,
                    buildTargets: [$0],
                    testTargets: [],
                    runTargets: [],
                    buildConfiguration: project.defaultDebugBuildConfigurationName
                )
            }
            let remainingTestTargetsSchemes = testTargets.map {
                createDefaultScheme(
                    name: $0.name,
                    autogeneratedSchemeProject: autogeneratedSchemeProject,
                    project: project,
                    buildTargets: [],
                    testTargets: [$0],
                    runTargets: [],
                    buildConfiguration: project.defaultDebugBuildConfigurationName
                )
            }
            let remainingRunTargetsSchemes = runTargets.map {
                createDefaultScheme(
                    name: $0.name,
                    autogeneratedSchemeProject: autogeneratedSchemeProject,
                    project: project,
                    buildTargets: [],
                    testTargets: [],
                    runTargets: [$0],
                    buildConfiguration: project.defaultDebugBuildConfigurationName
                )
            }
            autogeneratedSchemes = remainingBuildTargetsSchemes + remainingTestTargetsSchemes + remainingRunTargetsSchemes
        }

        return autogeneratedSchemes
    }

    private func mapAllProjectSchemes(
        project: inout Project,
        sideTable: inout GraphSideTable,
        allProjectsAutogeneratedSchemes: [AutogeneratedSchemes.AutogeneratedSchemeProject]
    ) throws -> [Scheme] {
        try allProjectsAutogeneratedSchemes.flatMap { allProjectsAutogeneratedScheme in
            try projectSchemes(
                project: &project,
                focusedTargets: sideTable.workspace.focusedTargets,
                autogeneratedSchemeProject: allProjectsAutogeneratedScheme
            )
        }
    }

    private func createPodSchemes(
        autogeneratedSchemeProject: AutogeneratedSchemes.AutogeneratedSchemeProject,
        project: Project,
        buildTargets: Set<Target>,
        testTargets: Set<Target>,
        runTargets: Set<Target>,
        buildConfiguration: String
    ) -> [Scheme] {
        var schemes = [Scheme]()

        schemes.append(contentsOf: buildTargets.filter { $0.product == .framework || $0.product == .staticFramework }.map { target in
            Scheme(
                name: target.name,
                shared: true,
                buildAction: .init(targets: [.init(projectPath: project.path, name: target.name)]),
                testAction: .testPlans(
                    autogeneratedSchemeProject.testPlans.compactMap { try? AbsolutePath(validatingAbsolutePath: $0) }
                )
            )
        })

        schemes.append(contentsOf: runTargets.map { target in
            Scheme(
                name: target.name,
                shared: true,
                buildAction: .init(targets: [.init(projectPath: project.path, name: target.name)])
            )
        })

        return schemes
    }

    // swiftlint:disable:next function_body_length
    private func createDefaultScheme(
        name: String,
        autogeneratedSchemeProject: AutogeneratedSchemes.AutogeneratedSchemeProject,
        project: Project,
        buildTargets: Set<Target>,
        testTargets: Set<Target>,
        runTargets: Set<Target>,
        buildConfiguration: String
    ) -> Scheme {
        var actualRunTarget: Target?

        if runTargets.count == 1,
           let runTarget = runTargets.first
        {
            actualRunTarget = runTarget
        } else {
            if let extensionTarget = buildTargets
                .first(where: { $0.product == .appExtension || $0.product == .messagesExtension })
            {
                actualRunTarget = hostAppTargetReference(for: extensionTarget, project: project)
            } else if let watch2ExtensionTarget = buildTargets.first(where: { $0.product == .watch2Extension }) {
                actualRunTarget = hostWatchAppTargetReference(for: watch2ExtensionTarget, project: project)
            } else {
                actualRunTarget = nil
            }
        }

        let runAction = actualRunTarget.map {
            RunAction(
                configuration: .configuration(buildConfiguration),
                attachDebugger: true,
                customLLDBInitFile: nil,
                preActions: [],
                postActions: [],
                executable: .init(projectPath: project.path, name: $0.name),
                filePath: nil,
                arguments: defaultArguments(for: $0, additionalArguments: autogeneratedSchemeProject.runActionArguments),
                options: .init(
                    language: autogeneratedSchemeProject.runLanguage.map { SchemeLanguage(identifier: $0.identifier) },
                    region: autogeneratedSchemeProject.runRegion
                ),
                diagnosticsOptions: .init()
            )
        }

        // build targets should be first, because in case of extension schemes, the extension target should be the first one
        var buildTargetReferences = (
            buildTargets.sorted { $0.name < $1.name } + runTargets.sorted { $0.name < $1.name }
        )
        .map {
            TargetReference(projectPath: project.path, name: $0.name)
        }
        if let runActionTargetReference = runAction?.executable,
           !buildTargetReferences.contains(runActionTargetReference)
        {
            buildTargetReferences.append(runActionTargetReference)
        }

        let testableTargets: [TestableTarget] = testTargets
            .map {
                let parallel = autogeneratedSchemeProject.testingOptions.contains(.parallelizable)
                let randomExecution = autogeneratedSchemeProject.testingOptions.contains(.randomExecutionOrdering)
                return TestableTarget(
                    target: .init(projectPath: project.path, name: $0.name),
                    parallelizable: parallel,
                    randomExecutionOrdering: randomExecution
                )
            }
            .sorted { $0.target.name < $1.target.name }

        let buildAction: BuildAction
        if buildTargetReferences.isEmpty {
            buildAction = .init(targets: testableTargets.map(\.target))
        } else {
            buildAction = .init(targets: buildTargetReferences)
        }

        let schemeName: String
        if let suffix = autogeneratedSchemeProject.suffix {
            schemeName = "\(name)-\(suffix)"
        } else {
            schemeName = name
        }

        return Scheme(
            name: schemeName,
            shared: true,
            buildAction: buildAction,
            testAction: testableTargets.isEmpty ? nil : TestAction(
                targets: testableTargets,
                arguments: defaultArguments(for: testTargets.sorted { $0.name < $1.name }, additionalArguments: autogeneratedSchemeProject.testActionArguments),
                configurationName: buildConfiguration,
                attachDebugger: true,
                coverage: autogeneratedSchemeProject.codeCoverageEnabled,
                codeCoverageTargets: [],
                expandVariableFromTarget: nil,
                preActions: [],
                postActions: [],
                diagnosticsOptions: .init(performanceAntipatternCheckerEnabled: false),
                language: autogeneratedSchemeProject.testLanguage?.identifier,
                region: autogeneratedSchemeProject.testRegion,
                preferredScreenCaptureFormat: autogeneratedSchemeProject.testScreenCaptureFormat
            ),
            runAction: runAction
        )
    }

    private func defaultArguments(for targets: [Target], additionalArguments: Arguments?) -> Arguments? {
        targets.reduce(nil) { partialResult, target in
            guard let arguments = defaultArguments(for: target, additionalArguments: additionalArguments) else { return partialResult }
            guard let partialResult else { return arguments }
            return partialResult.merging(with: arguments)
        }
    }

    private func defaultArguments(for target: Target, additionalArguments: Arguments?) -> Arguments? {
        switch (defaultArguments(for: target), additionalArguments) {
        case let (defaultArguments?, additionalArguments?):
            defaultArguments.merging(with: additionalArguments)
        case let (defaultArguments?, nil):
            defaultArguments
        case let (nil, additionalArguments?):
            additionalArguments
        case (nil, nil):
            nil
        }
    }

    private func defaultArguments(for target: Target) -> Arguments? {
        if target.environmentVariables.isEmpty, target.launchArguments.isEmpty {
            return nil
        }
        return Arguments(environmentVariables: target.environmentVariables, launchArguments: target.launchArguments)
    }

    // swiftlint:disable:next function_body_length
    private func groupByName(
        buildTargets: inout Set<Target>,
        testTargets: inout Set<Target>,
        runTargets: inout Set<Target>,
        buildSuffixes: Set<String>,
        testSuffixes: Set<String>,
        runSuffixes: Set<String>
    ) -> [String: (build: Set<Target>, test: Set<Target>, run: Set<Target>)] { // swiftlint:disable:this large_tuple
        let longerFirst: (String, String) -> Bool = { $0.count > $1.count }
        let sortedBuildSuffixes = (buildSuffixes + [""]).sorted(by: longerFirst)
        let sortedTestSuffixes = (testSuffixes + [""]).sorted(by: longerFirst)
        let sortedRunSuffixes = (runSuffixes + [""]).sorted(by: longerFirst)
        let groupToBuildTargets: [String: Set<Target>] = buildTargets
            .map { target -> (name: String, target: Target) in
                for buildSuffix in sortedBuildSuffixes where target.name.hasSuffix(buildSuffix) {
                    let groupName = String(target.name.dropSuffix(buildSuffix))
                    buildTargets.remove(target)
                    return (name: groupName, target: target)
                }
                return (name: target.name, target: target)
            }
            .reduce(into: [:]) { result, nameAndTarget in
                result[nameAndTarget.name, default: []].insert(nameAndTarget.target)
            }

        let groupToTestTargets: [String: Set<Target>] = testTargets
            .map { target -> (name: String, target: Target) in
                for testSuffix in sortedTestSuffixes where target.name.hasSuffix(testSuffix) {
                    let groupName = String(target.name.dropSuffix(testSuffix))
                    testTargets.remove(target)
                    return (name: groupName, target: target)
                }
                return (name: target.name, target: target)
            }
            .reduce(into: [:]) { result, nameAndTarget in
                result[nameAndTarget.name, default: []].insert(nameAndTarget.target)
            }

        let groupToRunTargets: [String: Set<Target>] = runTargets
            .map { target -> (name: String, target: Target) in
                for runSuffix in sortedRunSuffixes where target.name.hasSuffix(runSuffix) {
                    let groupName: String
                    if groupToBuildTargets[target.name] != nil || groupToTestTargets[target.name] != nil {
                        // For example, if there is already a `MyAppTests` group, don't group the `MyApp` target in a separate
                        // `My` group, but use the same for both
                        groupName = target.name
                    } else {
                        groupName = String(target.name.dropSuffix(runSuffix))
                    }
                    runTargets.remove(target)
                    return (name: groupName, target: target)
                }
                return (name: target.name, target: target)
            }
            .reduce(into: [:]) { result, nameAndTarget in
                result[nameAndTarget.name, default: []].insert(nameAndTarget.target)
            }

        let allGroupNames = Set(groupToBuildTargets.keys).union(groupToTestTargets.keys).union(groupToRunTargets.keys)
        return Dictionary(uniqueKeysWithValues: allGroupNames.map { name in
            let buildTargets = groupToBuildTargets[name] ?? []
            let testTargets = groupToTestTargets[name] ?? []
            let runTargets = groupToRunTargets[name] ?? []
            let schemeName: String

            let targetsCount = buildTargets.count + testTargets.count + runTargets.count
            if targetsCount == 1 {
                // use target name as scheme name
                let singleTarget = buildTargets.first ?? testTargets.first ?? runTargets.first
                schemeName = singleTarget!.name // swiftlint:disable:this force_unwrapping
            } else {
                schemeName = name
            }
            return (
                schemeName,
                (
                    build: buildTargets,
                    test: testTargets,
                    run: runTargets
                )
            )
        })
    }

    private func hostAppTargetReference(for target: Target, project: Project) -> Target? {
        project.targets
            .filter { $0.product.canHostTests() && $0.dependencies.contains(where: { dependency in
                if case let .target(name, _, _) = dependency, name == target.name {
                    return true
                } else {
                    return false
                }
            }) }
            .sorted { $0.name < $1.name }
            .first
    }

    private func hostWatchAppTargetReference(for target: Target, project: Project) -> Target? {
        project.targets
            .filter { $0.product == .watch2App && $0.dependencies.contains(where: { dependency in
                if case let .target(name, _, _) = dependency, name == target.name {
                    return true
                } else {
                    return false
                }
            }) }
            .sorted { $0.name < $1.name }
            .first
    }
}
