import GekoCore
import GekoGraph
import GekoGraphTesting
import GekoSupport
import ProjectDescription
import XcodeProj
import XCTest

@testable import GekoGenerator
@testable import GekoSupportTesting

final class AutogeneratedXCTestPlanDescriptorGeneratorTests: XCTestCase {
    var subject: AutogeneratedXCTestPlanDescriptorGenerator!

    override func setUp() {
        super.setUp()
        subject = AutogeneratedXCTestPlanDescriptorGenerator()
    }

    override func tearDown() {
        subject = nil
        super.tearDown()
    }

    // MARK: - Test target selection

    func test_map_whenTestTargetSelection_all_includesAllTestBundleTargets() throws {
        // Given
        let (graphTraverser, generatedProjects) = try makeSubjectInputs(
            autogeneratedTestPlans: [
                .testPlan(name: "All.xctestplan", testTargetSelection: .all),
            ]
        )

        // When
        let (descriptors, _) = try subject.autogeneratedXCTestPlanDescriptorsAndGenerateMetadata(
            graphTraverser: graphTraverser,
            generatedProjects: generatedProjects,
            sideTable: .init()
        )

        // Then
        XCTAssertEqual(descriptors.count, 1)
        let descriptor = try XCTUnwrap(descriptors.first)
        XCTAssertEqual(descriptor.testTargets.count, 2)
        XCTAssertEqual(descriptor.testTargets.compactMap { $0.pbxTarget.name }, ["AppTests", "FrameworkTests"])
        XCTAssertEqual(
            descriptor.testTargets.map(\.containerPath),
            ["container:App.xcodeproj", "container:Framework/Framework.xcodeproj"]
        )
        XCTAssertEqual(descriptor.testTargets.map(\.isEnabled), [true, true])
        XCTAssertEqual(descriptor.testTargets.map(\.isParallelizable), [false, false])
    }

    func test_map_whenTestTargetSelection_specific_includesOnlyListedTargets() throws {
        // Given
        let (graphTraverser, generatedProjects) = try makeSubjectInputs(
            autogeneratedTestPlans: [
                .testPlan(
                    name: "Specific.xctestplan",
                    testTargetSelection: .specific([
                        "AppTests",
                        .target(
                            TestableTarget(
                                target: "FrameworkTests",
                                skipped: true,
                                parallelizable: true
                            ),
                        )
                    ])
                ),
            ]
        )

        // When
        let (descriptors, _) = try subject.autogeneratedXCTestPlanDescriptorsAndGenerateMetadata(
            graphTraverser: graphTraverser,
            generatedProjects: generatedProjects,
            sideTable: .init()
        )

        // Then
        let descriptor = try XCTUnwrap(descriptors.first)
        XCTAssertEqual(descriptor.testTargets.compactMap { $0.pbxTarget.name }, ["AppTests", "FrameworkTests"])
        // The skipped target is disabled, the parallelizable target is marked as such.
        XCTAssertEqual(descriptor.testTargets.map(\.isEnabled), [true, false])
        XCTAssertEqual(descriptor.testTargets.map(\.isParallelizable), [false, true])
    }

    func test_map_whenSpecificTargetMissing_andPolicyFail_throws() throws {
        // Given
        let (graphTraverser, generatedProjects) = try makeSubjectInputs(
            autogeneratedTestPlans: [
                .testPlan(
                    name: "Plan.xctestplan",
                    testTargetSelection: .specific(["MissingTarget"]),
                    missingTargetPolicy: .fail
                ),
            ]
        )

        // When / Then
        XCTAssertThrowsError(
            try subject.autogeneratedXCTestPlanDescriptorsAndGenerateMetadata(
                graphTraverser: graphTraverser,
                generatedProjects: generatedProjects,
                sideTable: .init()
            )
        ) { error in
            guard case AutogeneratedXCTestPlanDescriptorGeneratorError.specificTestableTargetNotFound(let testPlan, let target) = error else {
                return XCTFail("Expected specificTestableTargetNotFound, got \(error)")
            }
            XCTAssertEqual(testPlan, "Plan.xctestplan")
            XCTAssertEqual(target, "MissingTarget")
        }
    }

    func test_map_whenSpecificTargetMissing_andPolicySkipTestPlan_skipsWholePlan() throws {
        // Given
        let (graphTraverser, generatedProjects) = try makeSubjectInputs(
            autogeneratedTestPlans: [
                .testPlan(
                    name: "Plan.xctestplan",
                    testTargetSelection: .specific(["MissingTarget"]),
                    missingTargetPolicy: .skipTestPlan()
                ),
            ]
        )

        // When
        let (descriptors, _) = try subject.autogeneratedXCTestPlanDescriptorsAndGenerateMetadata(
            graphTraverser: graphTraverser,
            generatedProjects: generatedProjects,
            sideTable: .init()
        )

        // Then
        XCTAssertEmpty(descriptors)
    }

    func test_map_whenSpecificTargetMissing_andPolicyExcludeTarget_excludesOnlyMissingTarget() throws {
        // Given
        let (graphTraverser, generatedProjects) = try makeSubjectInputs(
            autogeneratedTestPlans: [
                .testPlan(
                    name: "Plan.xctestplan",
                    testTargetSelection: .specific(
                        [
                            .target("AppTests"),
                            .target("MissingTarget"),
                        ]
                    ),
                    missingTargetPolicy: .skipTarget()
                ),
            ]
        )

        // When
        let (descriptors, _) = try subject.autogeneratedXCTestPlanDescriptorsAndGenerateMetadata(
            graphTraverser: graphTraverser,
            generatedProjects: generatedProjects,
            sideTable: .init()
        )

        // Then
        let descriptor = try XCTUnwrap(descriptors.first)
        XCTAssertEqual(descriptor.testTargets.compactMap { $0.pbxTarget.name }, ["AppTests"])
    }

    // MARK: - Options

    func test_map_passesThroughConfigurationAndDefaultOptions() throws {
        // Given
        let (graphTraverser, generatedProjects) = try makeSubjectInputs(
            autogeneratedTestPlans: [
                .testPlan(
                    name: "Plan.xctestplan",
                    configurationOptions: .init(
                        environmentVariableEntries: [.init(key: "isUnitTesting", value: "YES")],
                        targetForVariableExpansion: "AppTests"
                    ),
                    defaultOptions: .init(
                        commandLineArgumentEntries: [.init(argument: "--arg", enabled: true)],
                        targetForVariableExpansion: "FrameworkTests"
                    ),
                    testTargetSelection: .all
                ),
            ]
        )

        // When
        let (descriptors, _) = try subject.autogeneratedXCTestPlanDescriptorsAndGenerateMetadata(
            graphTraverser: graphTraverser,
            generatedProjects: generatedProjects,
            sideTable: .init()
        )

        // Then
        let descriptor = try XCTUnwrap(descriptors.first)
        XCTAssertEqual(descriptor.configurationOptions?.environmentVariableEntries, [.init(key: "isUnitTesting", value: "YES")])
        XCTAssertEqual(descriptor.configurationOptionsTargetForVariableExpansion?.pbxTarget.name, "AppTests")
        XCTAssertEqual(descriptor.defaultOptions?.commandLineArgumentEntries, [.init(argument: "--arg", enabled: true)])
        XCTAssertEqual(descriptor.defaultOptionsTargetForVariableExpansion?.pbxTarget.name, "FrameworkTests")
        XCTAssertEqual(
            descriptor.configurationOptionsTargetForVariableExpansion?.containerPath,
            "container:App.xcodeproj"
        )
        XCTAssertEqual(
            descriptor.defaultOptionsTargetForVariableExpansion?.containerPath,
            "container:Framework/Framework.xcodeproj"
        )
    }

    func test_map_whenVariableExpansionTargetNotFound_andPolicyFail_throws() throws {
        // Given
        let (graphTraverser, generatedProjects) = try makeSubjectInputs(
            autogeneratedTestPlans: [
                .testPlan(
                    name: "Plan.xctestplan",
                    configurationOptions: .init(targetForVariableExpansion: "MissingTarget"),
                    testTargetSelection: .all,
                    missingTargetPolicy: .fail
                ),
            ]
        )

        // When / Then
        XCTAssertThrowsError(
            try subject.autogeneratedXCTestPlanDescriptorsAndGenerateMetadata(
                graphTraverser: graphTraverser,
                generatedProjects: generatedProjects,
                sideTable: .init()
            )
        ) { error in
            guard case AutogeneratedXCTestPlanDescriptorGeneratorError.targetForVariableExpansionNotFound(let target) = error else {
                return XCTFail("Expected targetForVariableExpansionNotFound, got \(error)")
            }
            XCTAssertEqual(target, "MissingTarget")
        }
    }

    func test_map_whenVariableExpansionTargetNotFound_andPolicySkipTestPlan_skipsPlan() throws {
        // Given
        let (graphTraverser, generatedProjects) = try makeSubjectInputs(
            autogeneratedTestPlans: [
                .testPlan(
                    name: "Plan.xctestplan",
                    configurationOptions: .init(targetForVariableExpansion: "MissingTarget"),
                    testTargetSelection: .all,
                    missingTargetPolicy: .skipTestPlan()
                ),
            ]
        )

        // When
        let (descriptors, _) = try subject.autogeneratedXCTestPlanDescriptorsAndGenerateMetadata(
            graphTraverser: graphTraverser,
            generatedProjects: generatedProjects,
            sideTable: .init()
        )

        // Then
        XCTAssertEmpty(descriptors)
    }

    func test_map_whenVariableExpansionTargetNotFound_andPolicyExcludeTarget_ignoresExpansionTarget() throws {
        // Given
        let (graphTraverser, generatedProjects) = try makeSubjectInputs(
            autogeneratedTestPlans: [
                .testPlan(
                    name: "Plan.xctestplan",
                    configurationOptions: .init(targetForVariableExpansion: "MissingTarget"),
                    testTargetSelection: .all,
                    missingTargetPolicy: .skipTarget()
                ),
            ]
        )

        // When
        let (descriptors, _) = try subject.autogeneratedXCTestPlanDescriptorsAndGenerateMetadata(
            graphTraverser: graphTraverser,
            generatedProjects: generatedProjects,
            sideTable: .init()
        )

        // Then
        let descriptor = try XCTUnwrap(descriptors.first)
        XCTAssertNil(descriptor.configurationOptionsTargetForVariableExpansion)
    }

    // MARK: - Path

    func test_map_whenNoPath_writesToDerivedDirectory() throws {
        // Given
        let (graphTraverser, generatedProjects) = try makeSubjectInputs(
            autogeneratedTestPlans: [
                .testPlan(name: "Generated.xctestplan", testTargetSelection: .all),
            ]
        )

        // When
        let (descriptors, _) = try subject.autogeneratedXCTestPlanDescriptorsAndGenerateMetadata(
            graphTraverser: graphTraverser,
            generatedProjects: generatedProjects,
            sideTable: .init()
        )

        // Then
        let descriptor = try XCTUnwrap(descriptors.first)
        XCTAssertEqual(
            descriptor.path,
            try AbsolutePath(validating: "/somepath/Workspace/Derived/TestPlans/Generated.xctestplan")
        )
    }

    func test_map_whenPathProvided_resolvesRelativeToManifestDirectory() throws {
        // Given
        let (graphTraverser, generatedProjects) = try makeSubjectInputs(
            autogeneratedTestPlans: [
                .testPlan(
                    name: "Generated.xctestplan",
                    path: try AbsolutePath(validating: "/somepath/Workspace/TestPlans/Geko"),
                    testTargetSelection: .all
                ),
            ]
        )

        // When
        let (descriptors, _) = try subject.autogeneratedXCTestPlanDescriptorsAndGenerateMetadata(
            graphTraverser: graphTraverser,
            generatedProjects: generatedProjects,
            sideTable: .init()
        )

        // Then
        let descriptor = try XCTUnwrap(descriptors.first)
        XCTAssertEqual(
            descriptor.path,
            try AbsolutePath(validating: "/somepath/Workspace/TestPlans/Geko/Generated.xctestplan")
        )
    }

    func test_map_whenNoTestPlans_returnsEmptyDescriptors() throws {
        // Given
        let (graphTraverser, generatedProjects) = try makeSubjectInputs(autogeneratedTestPlans: [])

        // When
        let (descriptors, metadata) = try subject.autogeneratedXCTestPlanDescriptorsAndGenerateMetadata(
            graphTraverser: graphTraverser,
            generatedProjects: generatedProjects,
            sideTable: .init()
        )

        // Then
        XCTAssertEmpty(descriptors)
        // The metadata always lists all test bundle targets, regardless of test plans.
        XCTAssertEqual(metadata.allTestTargets.map(\.target.name), ["AppTests", "FrameworkTests"])
    }

    // MARK: - Generate metadata

    func test_generateMetadata_mapsSideTableAndAllTestTargets() throws {
        // Given
        // Only the focused App project is generated, so `FrameworkTests` is excluded from the
        // generated projects and, consequently, from the metadata's test targets.
        let (graphTraverser, generatedProjects) = try makeSubjectInputs(
            autogeneratedTestPlans: [
                .testPlan(name: "Plan.xctestplan", testTargetSelection: .all),
            ],
            focusedProjects: true
        )
        var sideTable = GraphSideTable()
        sideTable.workspace.cacheEnabled = true
        sideTable.workspace.focusedTargets = ["AppTests"]

        // When
        let (_, metadata) = try subject.autogeneratedXCTestPlanDescriptorsAndGenerateMetadata(
            graphTraverser: graphTraverser,
            generatedProjects: generatedProjects,
            sideTable: sideTable
        )

        // Then
        XCTAssertTrue(metadata.cacheEnabled)
        XCTAssertEqual(metadata.focusedTargets, ["AppTests"])
        XCTAssertEqual(metadata.allTestTargets.map(\.target.name), ["AppTests"])
        XCTAssertEqual(metadata.allTestTargets.map(\.target.containerPath), ["container:App.xcodeproj"])
    }

    // MARK: - Errors

    func test_map_whenGeneratedProjectNotFound_throws() throws {
        // Given
        let (graphTraverser, _) = try makeSubjectInputs(
            autogeneratedTestPlans: [
                .testPlan(
                    name: "Plan.xctestplan",
                    testTargetSelection: .specific(["AppTests"])
                ),
            ]
        )

        // When / Then
        XCTAssertThrowsError(
            try subject.autogeneratedXCTestPlanDescriptorsAndGenerateMetadata(
                graphTraverser: graphTraverser,
                generatedProjects: [:],
                sideTable: .init()
            )
        ) { error in
            guard case AutogeneratedXCTestPlanDescriptorGeneratorError.generatedProjectNotFound(let targetName, let path) = error else {
                return XCTFail("Expected generatedProjectNotFound, got \(error)")
            }
            XCTAssertEqual(targetName, "AppTests")
            XCTAssertEqual(path, "/somepath/Workspace/App.xcodeproj")
        }
    }

    func test_map_whenGeneratedProjectMissingTarget_throws() throws {
        // Given
        let (graphTraverser, _) = try makeSubjectInputs(
            autogeneratedTestPlans: [
                .testPlan(
                    name: "Plan.xctestplan",
                    testTargetSelection: .specific(["AppTests"])
                ),
            ]
        )
        let xcodeProjPath = try AbsolutePath(validating: "/somepath/Workspace/App.xcodeproj")
        let generatedProjects = [
            xcodeProjPath: GeneratedProject(
                pbxproj: .init(),
                path: xcodeProjPath,
                targets: [:],
                name: "App.xcodeproj"
            ),
        ]

        // When / Then
        XCTAssertThrowsError(
            try subject.autogeneratedXCTestPlanDescriptorsAndGenerateMetadata(
                graphTraverser: graphTraverser,
                generatedProjects: generatedProjects,
                sideTable: .init()
            )
        ) { error in
            guard case AutogeneratedXCTestPlanDescriptorGeneratorError.generatedProjectNotFound(let targetName, let path) = error else {
                return XCTFail("Expected generatedProjectNotFound, got \(error)")
            }
            XCTAssertEqual(targetName, "AppTests")
            XCTAssertEqual(path, "/somepath/Workspace/App.xcodeproj")
        }
    }

    // MARK: - Helpers

    private func makeSubjectInputs(
        autogeneratedTestPlans: [AutogeneratedTestPlan],
        generatedProjects: [AbsolutePath: GeneratedProject]? = nil,
        focusedProjects: Bool = false
    ) throws -> (GraphTraverser, [AbsolutePath: GeneratedProject]) {
        // The `.xcworkspace` and `.xcodeproj` live in the same root project folder.
        let workspacePath = try AbsolutePath(validating: "/somepath/Workspace")
        let appXcodeProjPath = try AbsolutePath(validating: "/somepath/Workspace/App.xcodeproj")
        let frameworkPath = try AbsolutePath(validating: "/somepath/Workspace/Framework")
        let frameworkXcodeProjPath = try AbsolutePath(validating: "/somepath/Workspace/Framework/Framework.xcodeproj")

        let app = Target.test(name: "App", product: .app)
        let appTests = Target.test(
            name: "AppTests",
            product: .unitTests,
            dependencies: [.target(name: "App")]
        )
        let framework = Target.test(name: "Framework", product: .framework)
        let frameworkTests = Target.test(
            name: "FrameworkTests",
            product: .unitTests,
            dependencies: [.target(name: "Framework")]
        )

        let appProject = Project.test(
            path: workspacePath,
            xcodeProjPath: appXcodeProjPath,
            name: "App",
            targets: [app, appTests]
        )
        let frameworkProject = Project.test(
            path: frameworkPath,
            xcodeProjPath: frameworkXcodeProjPath,
            name: "Framework",
            targets: [framework, frameworkTests]
        )

        var generationOptions = Workspace.GenerationOptions.test()
        generationOptions.autogeneratedTestPlans = autogeneratedTestPlans
        let workspace = Workspace.test(
            path: workspacePath,
            xcWorkspacePath: workspacePath.appending(component: "Workspace.xcworkspace"),
            name: "Workspace",
            generationOptions: generationOptions
        )

        let projects = if focusedProjects {
            [appProject.path: appProject]
        } else {
            [
                appProject.path: appProject,
                frameworkProject.path: frameworkProject
            ]
        }
        let targets = if focusedProjects {
            [appProject.path: [app.name: app, appTests.name: appTests]]
        } else {
            [
                appProject.path: [app.name: app, appTests.name: appTests],
                frameworkProject.path: [framework.name: framework, frameworkTests.name: frameworkTests],
            ]
        }

        let graph = Graph.test(
            workspace: workspace,
            projects: projects,
            targets: targets
        )

        let resolvedGeneratedProjects = generatedProjects ?? makeGeneratedProjects(
            projects: focusedProjects ? [appProject] : [appProject, frameworkProject]
        )

        return (GraphTraverser(graph: graph), resolvedGeneratedProjects)
    }

    private func makeGeneratedProjects(projects: [Project]) -> [AbsolutePath: GeneratedProject] {
        Dictionary(uniqueKeysWithValues: projects.map { project in
            var pbxTargets: [String: PBXNativeTarget] = [:]
            project.targets.forEach { pbxTargets[$0.name] = PBXNativeTarget(name: $0.name) }
            return (
                project.xcodeProjPath,
                GeneratedProject(
                    pbxproj: .init(),
                    path: project.xcodeProjPath,
                    targets: pbxTargets,
                    name: project.xcodeProjPath.basename
                )
            )
        })
    }
}
