import Foundation
import GekoCore
import GekoSupport
import GekoGraph
import ProjectDescription

/// Geko Workspace Identifier Mapper
///
/// A mapper that includes a known file within the generated xcworkspace directory.
/// This is used to help identify the workspace as one that has been generated by geko.
final class GekoWorkspaceIdentifierMapper: WorkspaceMapping {
    public func map(
        workspace: inout WorkspaceWithProjects,
        sideTable: inout WorkspaceSideTable
    ) throws -> [SideEffectDescriptor] {
        let gekoGeneratedFileDescriptor = FileDescriptor(
            path: workspace
                .workspace
                .xcWorkspacePath
                .appending(
                    component: Constants.gekoGeneratedFileName
                )
        )

        return [.file(gekoGeneratedFileDescriptor)]
    }
}
