import SwiftUI

extension Image {
    static let edit = Image(systemName: "pencil")
    static let about = Image(systemName: "questionmark.circle")
    static let copy = Image(systemName: "doc.on.doc")
    static let delete = Image(systemName: "trash")
    static let downArrow = Image(systemName: "chevron.down")
    static let upArrow = Image(systemName: "chevron.up")
    static let visible = Image(systemName: "eye")
    static let invisible = Image(systemName: "eye.slash")
    static let targetItem = Image(systemName: "t.square.fill")
    static let developmentConfigItem = Image(systemName: "hammer.circle")
    static let textformat = Image(systemName: "character.cursor.ibeam")
    static let danger = Image(systemName: "exclamationmark.triangle.fill")
    static let rightChevron = Image(systemName: "chevron.right")
    static let profileItem = Image(systemName: "gear")
    static let checkmark = Image(systemName: "checkmark.circle")
    static let closeCircle = Image(systemName: "xmark.circle.fill")
    static let close = Image(systemName: "xmark")
    static let search = Image(systemName: "magnifyingglass")
    static let play = Image(systemName: "play.fill")
    static let stop = Image(systemName: "square.fill")
    static let refresh = Image(systemName: "arrow.counterclockwise")
    static let folder = Image(systemName: "folder")
    static let branch = Image(systemName: "arrow.triangle.branch")
    static let device = Image(systemName: "macbook.and.iphone")
    static let simulator = Image(systemName: "iphone")
    static let internalScript = Image(systemName: "gear")
    static let compactArrowRight = Image(systemName: "chevron.compact.right")
    static let failureTriangle = Image(systemName: "exclamationmark.triangle.fill")
    static let terminal = Image(systemName: "apple.terminal")
    static let willOpenArrow = Image(systemName: "chevron.right")
    static let didOpenArrow = Image(systemName: "chevron.down")
    static let plus = Image(systemName: "plus")

    static let framework = Image(systemName: "latch.2.case.fill")
    static let projectItem = Image(systemName: "character.book.closed.fill")
    static let applicationItem = Image(systemName: "a.square.fill")
    static let extensionItem = Image(systemName: "e.square.fill")
    static let testsItem = Image(systemName: "checkmark.diamond.fill")
    static let checkmarkFill = Image(systemName: "checkmark.circle.fill")
    static let bundleItem = Image(systemName: "batteryblock.fill")
    static let libraryItem = Image(systemName: "building.columns")
    static let unknownTargetType = Image(systemName: "questionmark.square")
    static let appLogo = Image("logo")
    static let swift = Image(systemName: "swift")
    static let xcode = Image("XcodeIcon")
    static let cloud = Image(systemName: "externaldrive.badge.icloud")
    
    // Sidebar
    static let shortcuts = Image(systemName: "square.3.layers.3d")
    static let house = Image(systemName: "house")
    static let projectGeneration = Image(systemName: "power")
    static let logs = Image(systemName: "book.and.wrench")
    static let settings = Image(systemName: "gear")
}
