@preconcurrency import ProjectDescription
import Foundation

let workspace = Workspace(
    name: "App",
    projects: [
        "./"
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled,
        commonSettings: [["IPHONEOS_DEPLOYMENT_TARGET": "15.0"]]
    )
)
