import ProjectDescription

extension AutogeneratedTestPlan.Options {

    func map(
        targetForVariableExpansion: AutogeneratedXCTestPlanDescriptor.TestTarget?
    ) -> AutogeneratedXCTestPlan.Options {

        let targetForVariableExpansion = targetForVariableExpansion.map { target in
            AutogeneratedXCTestPlan.TestTargetReference(
                containerPath: target.containerPath,
                identifier: target.pbxTarget.uuid,
                name: target.pbxTarget.name
            )
        }

        let convertedMallocStackLoggingOptions: AutogeneratedXCTestPlan.Options.MallocStackLoggingOptions? = {
            switch mallocStackLoggingOptions {
            case .on: .on()
            case .off, .none: nil
            }
        }()

        return AutogeneratedXCTestPlan.Options(
            commandLineArgumentEntries: commandLineArgumentEntries,
            environmentVariableEntries: environmentVariableEntries,
            targetForVariableExpansion: targetForVariableExpansion,
            language: language,
            region: region,
            locationScenario: locationScenario,
            uiTestingScreenshotsLifetime: uiTestingScreenshotsLifetime,
            preferredScreenCaptureFormat: preferredScreenCaptureFormat,
            areLocalizationScreenshotsEnabled: areLocalizationScreenshotsEnabled,
            distributor: distributor,
            userAttachmentLifetime: userAttachmentLifetime,
            diagnosticCollectionPolicy: diagnosticCollectionPolicy,
            testExecutionOrdering: testExecutionOrdering,
            testTimeoutsEnabled: testTimeoutsEnabled,
            defaultTestExecutionTimeAllowance: defaultTestExecutionTimeAllowance,
            maximumTestExecutionTimeAllowance: maximumTestExecutionTimeAllowance,
            testRepetitionMode: testRepetitionMode,
            maximumTestRepetitions: maximumTestRepetitions,
            repeatInNewRunnerProcess: repeatInNewRunnerProcess,
            codeCoverage: codeCoverage,
            addressSanitizer: addressSanitizer,
            threadSanitizerEnabled: threadSanitizerEnabled,
            undefinedBehaviorSanitizerEnabled: undefinedBehaviorSanitizerEnabled,
            mainThreadCheckerDetectionPolicy: mainThreadCheckerDetectionPolicy,
            threadPerformanceCheckerRuntimeIssueDetection: threadPerformanceCheckerRuntimeIssueDetection,
            runtimeIssueDetection: runtimeIssueDetection,
            checkedAllocations: checkedAllocations,
            mallocScribbleEnabled: mallocScribbleEnabled,
            mallocGuardEdgesEnabled: mallocGuardEdgesEnabled,
            nsZombieEnabled: nsZombieEnabled,
            mallocStackLoggingOptions: convertedMallocStackLoggingOptions,
        )
    }
}
