@preconcurrency import ProjectDescription
import Foundation

let workspace = Workspace(
    name: "App",
    projects: [
        "./"
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled,
        autogenerateLocalPodsProjects: .enabled(
            [
                "LocalPods/Common/**/*.podspec",
                "LocalPods/Feature/**/*.podspec"
            ]
        ),
        generateSharedTestTarget: .init(
            installTo: "App",
            targets: [
                .generate(name: "LocalPodsUnitTests", testsPattern: ".*-Unit-Tests")
            ]
        ),
        commonSettings: [["IPHONEOS_DEPLOYMENT_TARGET": "15.0"]]
    )
)
