
import Foundation
import ProjectDescription

public struct AutogeneratedXCTestPlan: Codable, Equatable, Sendable {
    public struct Options: Codable, Equatable, Sendable {
        public struct MallocStackLoggingOptions: Codable, Equatable, Sendable {
            public enum LoggingType: String, Codable, Equatable, Sendable {
                case liveAllocations
            }

            enum CodingKeys: String, CodingKey {
                case loggingType
            }

            public var loggingType: LoggingType?

            public init(loggingType: LoggingType?) {
                self.loggingType = loggingType
            }

            public static func on() -> Self { Self(loggingType: .liveAllocations) }
            public static func off() -> Self? { nil }
        }

        public let commandLineArgumentEntries: [AutogeneratedTestPlan.Options.CommandLineArgumentEntry]?
        public let environmentVariableEntries: [AutogeneratedTestPlan.Options.VariableEntity]?
        public let targetForVariableExpansion: TestTargetReference?
        public let language: String?
        public let region: String?
        public let locationScenario: AutogeneratedTestPlan.Options.LocationScenario?
        public let uiTestingScreenshotsLifetime: AutogeneratedTestPlan.Options.UITestingScreenshotsLifetime?
        public let preferredScreenCaptureFormat: AutogeneratedTestPlan.Options.PreferredScreenCaptureFormat?
        public let areLocalizationScreenshotsEnabled: Bool?
        public let distributor: AutogeneratedTestPlan.Options.Distributor?
        public let userAttachmentLifetime: AutogeneratedTestPlan.Options.UserAttachmentLifetime?
        public let diagnosticCollectionPolicy: AutogeneratedTestPlan.Options.DiagnosticCollectionPolicy?
        public let testExecutionOrdering:  AutogeneratedTestPlan.Options.TestExecutionOrdering?
        public let testTimeoutsEnabled: Bool?
        public let defaultTestExecutionTimeAllowance: Int?
        public let maximumTestExecutionTimeAllowance: Int?
        public let testRepetitionMode: AutogeneratedTestPlan.Options.TestRepetitionMode?
        public let maximumTestRepetitions: Int?
        public let repeatInNewRunnerProcess: Bool?
        public let codeCoverage: Bool?
        public let addressSanitizer: AutogeneratedTestPlan.Options.AddressSanitizer?
        public let threadSanitizerEnabled: Bool?
        public let undefinedBehaviorSanitizerEnabled: Bool?
        public let mainThreadCheckerDetectionPolicy: AutogeneratedTestPlan.Options.RuntimeApiChecking?
        public let threadPerformanceCheckerRuntimeIssueDetection: AutogeneratedTestPlan.Options.RuntimeApiChecking?
        public let runtimeIssueDetection: AutogeneratedTestPlan.Options.RuntimeApiChecking?
        public let checkedAllocations: AutogeneratedTestPlan.Options.CheckedAllocations?
        public let mallocScribbleEnabled: Bool?
        public let mallocGuardEdgesEnabled: Bool?
        public let nsZombieEnabled: Bool?
        public let mallocStackLoggingOptions: MallocStackLoggingOptions?

        public init(
            commandLineArgumentEntries: [AutogeneratedTestPlan.Options.CommandLineArgumentEntry]?,
            environmentVariableEntries: [AutogeneratedTestPlan.Options.VariableEntity]?,
            targetForVariableExpansion: TestTargetReference?,
            language: String?,
            region: String?,
            locationScenario: AutogeneratedTestPlan.Options.LocationScenario?,
            uiTestingScreenshotsLifetime: AutogeneratedTestPlan.Options.UITestingScreenshotsLifetime?,
            preferredScreenCaptureFormat: AutogeneratedTestPlan.Options.PreferredScreenCaptureFormat?,
            areLocalizationScreenshotsEnabled: Bool?,
            distributor: AutogeneratedTestPlan.Options.Distributor?,
            userAttachmentLifetime: AutogeneratedTestPlan.Options.UserAttachmentLifetime?,
            diagnosticCollectionPolicy: AutogeneratedTestPlan.Options.DiagnosticCollectionPolicy?,
            testExecutionOrdering: AutogeneratedTestPlan.Options.TestExecutionOrdering?,
            testTimeoutsEnabled: Bool?,
            defaultTestExecutionTimeAllowance: Int?,
            maximumTestExecutionTimeAllowance: Int?,
            testRepetitionMode: AutogeneratedTestPlan.Options.TestRepetitionMode?,
            maximumTestRepetitions: Int?,
            repeatInNewRunnerProcess: Bool?,
            codeCoverage: Bool?,
            addressSanitizer: AutogeneratedTestPlan.Options.AddressSanitizer?,
            threadSanitizerEnabled: Bool?,
            undefinedBehaviorSanitizerEnabled: Bool?,
            mainThreadCheckerDetectionPolicy: AutogeneratedTestPlan.Options.RuntimeApiChecking?,
            threadPerformanceCheckerRuntimeIssueDetection: AutogeneratedTestPlan.Options.RuntimeApiChecking?,
            runtimeIssueDetection: AutogeneratedTestPlan.Options.RuntimeApiChecking?,
            checkedAllocations: AutogeneratedTestPlan.Options.CheckedAllocations?,
            mallocScribbleEnabled: Bool?,
            mallocGuardEdgesEnabled: Bool?,
            nsZombieEnabled: Bool?,
            mallocStackLoggingOptions: MallocStackLoggingOptions?,
        ) {
            self.commandLineArgumentEntries = commandLineArgumentEntries
            self.environmentVariableEntries = environmentVariableEntries
            self.targetForVariableExpansion = targetForVariableExpansion
            self.language = language
            self.region = region
            self.locationScenario = locationScenario
            self.uiTestingScreenshotsLifetime = uiTestingScreenshotsLifetime
            self.preferredScreenCaptureFormat = preferredScreenCaptureFormat
            self.areLocalizationScreenshotsEnabled = areLocalizationScreenshotsEnabled
            self.distributor = distributor
            self.userAttachmentLifetime = userAttachmentLifetime
            self.diagnosticCollectionPolicy = diagnosticCollectionPolicy
            self.testExecutionOrdering = testExecutionOrdering
            self.testTimeoutsEnabled = testTimeoutsEnabled
            self.defaultTestExecutionTimeAllowance = defaultTestExecutionTimeAllowance
            self.maximumTestExecutionTimeAllowance = maximumTestExecutionTimeAllowance
            self.testRepetitionMode = testRepetitionMode
            self.maximumTestRepetitions = maximumTestRepetitions
            self.repeatInNewRunnerProcess = repeatInNewRunnerProcess
            self.codeCoverage = codeCoverage
            self.addressSanitizer = addressSanitizer
            self.threadSanitizerEnabled = threadSanitizerEnabled
            self.undefinedBehaviorSanitizerEnabled = undefinedBehaviorSanitizerEnabled
            self.mainThreadCheckerDetectionPolicy = mainThreadCheckerDetectionPolicy
            self.threadPerformanceCheckerRuntimeIssueDetection = threadPerformanceCheckerRuntimeIssueDetection
            self.runtimeIssueDetection = runtimeIssueDetection
            self.checkedAllocations = checkedAllocations
            self.mallocScribbleEnabled = mallocScribbleEnabled
            self.mallocGuardEdgesEnabled = mallocGuardEdgesEnabled
            self.nsZombieEnabled = nsZombieEnabled
            self.mallocStackLoggingOptions = mallocStackLoggingOptions
        }

        static let empty = Self(
            commandLineArgumentEntries: nil,
            environmentVariableEntries: nil,
            targetForVariableExpansion: nil,
            language: nil,
            region: nil,
            locationScenario: nil,
            uiTestingScreenshotsLifetime: nil,
            preferredScreenCaptureFormat: nil,
            areLocalizationScreenshotsEnabled: nil,
            distributor: nil,
            userAttachmentLifetime: nil,
            diagnosticCollectionPolicy: nil,
            testExecutionOrdering: nil,
            testTimeoutsEnabled: nil,
            defaultTestExecutionTimeAllowance: nil,
            maximumTestExecutionTimeAllowance: nil,
            testRepetitionMode: nil,
            maximumTestRepetitions: nil,
            repeatInNewRunnerProcess: nil,
            codeCoverage: nil,
            addressSanitizer: nil,
            threadSanitizerEnabled: nil,
            undefinedBehaviorSanitizerEnabled: nil,
            mainThreadCheckerDetectionPolicy: nil,
            threadPerformanceCheckerRuntimeIssueDetection: nil,
            runtimeIssueDetection: nil,
            checkedAllocations: nil,
            mallocScribbleEnabled: nil,
            mallocGuardEdgesEnabled: nil,
            nsZombieEnabled: nil,
            mallocStackLoggingOptions: nil,
        )
    }

    public struct Configuration: Codable, Equatable, Sendable {
        public let id: UUID
        public let name: String
        public let options: Options?

        public init(id: UUID, name: String, options: Options? = nil) {
            self.id = id
            self.name = name
            self.options = options
        }
    }

    public struct TestTargetReference: Codable, Equatable, Sendable {
        /// Path to the target's container, prefixed with `container:` (e.g. `container:App.xcodeproj`).
        public let containerPath: String

        /// Blueprint identifier of the PBX target the entry references.
        public let identifier: String

        /// Name of the test target.
        public let name: String

        public init(containerPath: String, identifier: String, name: String) {
            self.containerPath = containerPath
            self.identifier = identifier
            self.name = name
        }
    }

    public struct TestTarget: Codable, Equatable, Sendable {
        /// Whether the target runs. Omitted in the JSON when `true`; Xcode defaults to enabled.
        public let enabled: Bool?

        /// Whether the target runs in parallel with other targets.
        public let parallelizable: Bool?

        public let target: TestTargetReference

        public init(
            target: TestTargetReference,
            enabled: Bool? = nil,
            parallelizable: Bool? = nil
        ) {
            self.enabled = enabled
            self.parallelizable = parallelizable
            self.target = target
        }
    }

    public let configurations: [Configuration]?
    public let defaultOptions: Options?
    public var testTargets: [TestTarget]
    public let version: Int?

    public init(
        testTargets: [TestTarget],
        configurations: [Configuration]? = nil,
        defaultOptions: Options? = nil,
        version: Int? = nil
    ) {
        self.configurations = configurations
        self.defaultOptions = defaultOptions
        self.testTargets = testTargets
        self.version = version
    }
}
