import Foundation

/// The structure defining the output schema of a Xcode workspace.
public struct Workspace: Codable, Equatable {
    /// The name of the workspace. Also, the file name of the generated Xcode workspace.
    public var name: String

    /// Path to where the manifest / root directory of this workspace is located
    public let path: String
    
    /// The custom schemes for the workspace. Default schemes for each target are generated by default.
    public var schemes: [Scheme]

    public init(
        name: String,
        path: String,
        schemes: [Scheme] = [Scheme]()
    ) {
        self.name = name
        self.path = path
        self.schemes = schemes
    }
}
