name: build_and_test

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test_macos:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - id: only_docs_changes
        uses: ./.github/actions/only-docs-changes

      - uses: ./.github/actions/xcode-select
        if: steps.only_docs_changes.outputs.run == 'true'

      - uses: actions/cache@v4
        if: steps.only_docs_changes.outputs.run == 'true'
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: build_and_test
        if: steps.only_docs_changes.outputs.run == 'true'
        run: |
          set -o pipefail && xcrun swift test | xcbeautify --renderer github-actions --is-ci

  build_and_test_linux:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      GH_USER: ${{ secrets.GH_USER }}
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - id: only_docs_changes
        uses: ./.github/actions/only-docs-changes

      - uses: ./.github/actions/show-swift-version
        if: steps.only_docs_changes.outputs.run == 'true'

      - name: build_and_test
        if: steps.only_docs_changes.outputs.run == 'true'
        run: |
          swift test \
            --filter GekoAcceptanceTests \
            --filter GekoSupportTests \
            --filter GekoCoreIntegrationTests \
            --filter GekoCocoapodsTests \
            --filter GekoCoreTests \
            --filter GekoDependenciesTests \
            --filter GekoGraphTests \
            --filter GekoKitTests \
            --filter ProjectDescriptionTests \
            --filter PubGrubTests \

  build_and_test_gekodesktop:
    name: Build and Test GekoDesktop
    runs-on: macos-26
    env:
      OUTPUT_DIR: "GekoDesktop/test_output"
    steps:
      - uses: actions/checkout@v6.0.1
        with:
            persist-credentials: false
            fetch-depth: 0

      - id: only_docs_changes
        uses: ./.github/actions/only-docs-changes

      - name: Install Xcodegen
        if: steps.only_docs_changes.outputs.run == 'true'
        run: brew install xcodegen

      - name: Build Release Binary
        if: steps.only_docs_changes.outputs.run == 'true'
        run: |
          (cd GekoDesktop && xcodegen generate)
          fastlane scan \
            --project "GekoDesktop/GekoDesktop.xcodeproj" \
            --destination "platform=macOS" \
            --scheme GekoDesktop \
            --output_directory "$OUTPUT_DIR" \
            --skip_slack true \
            --buildlog_path "$OUTPUT_DIR" \
            --result_bundle true \
            --xcargs "-skipPackagePluginValidation" \
            --xcodebuild_formatter xcbeautify
